#!/usr/bin/env python3
"""analyse.py — per-run postprocess for run_free_wp_L50_E25_sigma1_v2.

Free-space counterpart of run_wp_n162_L50_E25_sigma1_v2. Runs the same
pipeline phases as the jellium WP run so that every output directory and
plot name matches; phases that require bath states (eigenvalues_gs,
gamma_transitions, overlap, orbitals) will gracefully skip.

The primary use of this run is to compute the bath-isolated density
response:  δn_bath(r,t) = δn_jellium(r,t) - δn_free(r,t)

Usage:
    cd <this dir>
    /local/data/public/skcb2/tddft/venv/bin/python3 analyse.py
"""
from __future__ import annotations

import re
import sys
import textwrap
from pathlib import Path

import pandas as pd

HA_TO_EV = 27.211386245988

RUN_DIR     = Path(__file__).resolve().parent
RESULTS_DIR = RUN_DIR / "results"
ANALYSIS    = RESULTS_DIR / "analysis"
SUMMARY     = RESULTS_DIR / "run_summary.txt"

PIPELINE_PHASES: tuple[str, ...] = (
    "summary",
    "gs",
    "layout",
    "observables",
    "eigenvalues_gs",
    "gamma_transitions",
    "wp_trajectory",
    "state_energies",
    "state_energy_spectra",
    "occupations",
    "momentum",
    "knudsen_ke",
    "kl_divergence",
    "energy_balance",
    "density",
    "overlap",
    "orbitals",
)


def read_summary_value(path: Path, key: str, default=None):
    if not path.exists():
        return default
    m = re.search(rf"^\s*{re.escape(key)}\s*=\s*(\S+)",
                  path.read_text(), flags=re.MULTILINE)
    if not m:
        return default
    s = m.group(1)
    try:
        return float(s)
    except ValueError:
        return s


def physics_block() -> dict:
    obs_dir = RESULTS_DIR / "raw" / "observables"
    csv = obs_dir / "observables.csv"
    if not csv.exists():
        return {"n_frames": 0, "total_time_au": float("nan"),
                "dE_total_eV": float("nan"), "dE_kinetic_eV": float("nan"),
                "dE_hartree_eV": float("nan"), "dE_xc_eV": float("nan"),
                "sum_components_eV": float("nan"),
                "dipole_z0": float("nan"), "dipole_z1": float("nan"),
                "dipole_z_advance": float("nan")}
    obs = pd.read_csv(csv, comment="#")

    wE0  = float(obs["energy_total"].iloc[0])
    wE1  = float(obs["energy_total"].iloc[-1])
    wEk0, wEk1 = float(obs["energy_kinetic"].iloc[0]), float(obs["energy_kinetic"].iloc[-1])

    dEh = 0.0
    if "energy_hartree" in obs.columns:
        dEh = (float(obs["energy_hartree"].iloc[-1]) - float(obs["energy_hartree"].iloc[0]))
    dEx = 0.0
    if "energy_xc" in obs.columns:
        dEx = (float(obs["energy_xc"].iloc[-1]) - float(obs["energy_xc"].iloc[0]))

    has_dz = "dipole_z" in obs.columns
    dz0 = float(obs["dipole_z"].iloc[0]) if has_dz else float("nan")
    dz1 = float(obs["dipole_z"].iloc[-1]) if has_dz else float("nan")

    dEk = wEk1 - wEk0
    dEt = wE1 - wE0

    return {
        "dE_total_eV":   dEt * HA_TO_EV,
        "dE_kinetic_eV": dEk * HA_TO_EV,
        "dE_hartree_eV": dEh * HA_TO_EV,
        "dE_xc_eV":      dEx * HA_TO_EV,
        "sum_components_eV": (dEk + dEh + dEx) * HA_TO_EV,
        "dipole_z0":         dz0,
        "dipole_z1":         dz1,
        "dipole_z_advance":  dz1 - dz0,
        "n_frames":          len(obs),
        "total_time_au":     float(obs["time_au"].iloc[-1])
                              if "time_au" in obs.columns else float("nan"),
    }


def render_markdown(phys: dict, rs: dict, pipe_log: dict) -> str:
    md = f"""# Analysis: {RUN_DIR.name}  (FREE counterpart)

Auto-generated by `{Path(__file__).name}`. Non-interacting free-space WP
propagation — counterpart of `run_wp_n162_L50_E25_sigma1_v2`.

Use for:  δn_bath(r,t) = δn_jellium(r,t) - δn_free(r,t)

## Run identity

| Field | Value |
|---|---|
| Run dir | `{RUN_DIR}` |
| Cell | {rs.get('cell_bohr', '?')} (cubic, periodic) |
| Spacing | {rs.get('spacing_bohr', '?')} Bohr |
| Theory | non-interacting (no Hartree, no XC) |
| WP energy | {rs.get('wp_energy_ev', '?')} eV |
| WP σ | {rs.get('wp_sigma_bohr', '?')} Bohr |
| WP k₀ | {rs.get('wp_k0_bohr_inv', '?')} |
| WP launch | {rs.get('wp_center_bohr', '?')} Bohr |
| dt × N_steps | {rs.get('dt_au','?')} × {rs.get('rt_num_steps','?')} (= {phys['total_time_au']:.3f} a.u.) |
| Wall time | {rs.get('wall_time_s', '?')} s |

## Energy budget (non-interacting — expect ΔE ≈ 0)

| Term | Value |
|---|---|
| Δ E_total       | {phys['dE_total_eV']*1e6:+.4f} μeV  (conservation residual) |
| Δ E_kinetic     | {phys['dE_kinetic_eV']:+.4f} eV |
| Δ E_hartree     | {phys['dE_hartree_eV']:+.4f} eV  (should be 0 — non-interacting) |
| Δ E_xc          | {phys['dE_xc_eV']:+.4f} eV  (should be 0 — non-interacting) |

## WP centroid advance (from dipole_z proxy)

| Quantity | Value |
|---|---|
| dipole_z(0)       | {phys['dipole_z0']:+.4f} |
| dipole_z(end)     | {phys['dipole_z1']:+.4f} |
| Advance Δdipole_z | {phys['dipole_z_advance']:+.4f} |

## Postprocess pipeline outcome

"""
    for ph in PIPELINE_PHASES:
        flag = pipe_log.get(ph, "skip")
        md += f"- **{ph}**: {flag}\n"
    md += textwrap.dedent(f"""
## Output layout

```
results/analysis/observables/
├── observables_summary.png
├── total_energy_vs_time.png, all_energies_vs_time.png
├── current_components_vs_time.png, dipole_components_vs_time.png
├── density_fluctuation_l2.png
├── fft_total_energy.png, fft_current_*.png, dipole_spectrum_*.png
├── wp_position_vs_time.png, wp_velocity_vs_time.png
├── momentum_distribution.gif, momentum_heatmap.png
├── knudsen_ke_vs_t.png, kl_divergence_vs_t.png
└── density/                                       (VTI density animations)
```
""")
    return md


def install_schema_shims() -> list[str]:
    """Bridge path-schema mismatches (same as jellium WP analyse.py)."""
    log: list[str] = []
    pairs = [
        (RESULTS_DIR / "raw" / "overlap",
         RESULTS_DIR / "raw" / "observables" / "overlap"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_total",
         RESULTS_DIR / "raw" / "vti" / "density_total"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_system",
         RESULTS_DIR / "raw" / "vti" / "density_system"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta",
         RESULTS_DIR / "raw" / "vti" / "density_delta"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta_coarse",
         RESULTS_DIR / "raw" / "vti" / "density_delta_coarse"),
    ]
    for link, target in pairs:
        if link.exists() or link.is_symlink():
            continue
        if not target.exists():
            continue
        link.parent.mkdir(parents=True, exist_ok=True)
        link.symlink_to(target.resolve())
        log.append(f"  symlink {link.name} → {target.name}")
    return log


def main() -> int:
    if not RESULTS_DIR.exists():
        print(f"FATAL: {RESULTS_DIR} does not exist", file=sys.stderr)
        return 2

    try:
        from inqview.postprocess import pipeline
    except ImportError:
        sys.path.insert(0, "/local/data/public/skcb2/tddft/inq-stack/python")
        from inqview.postprocess import pipeline

    print(f"=== analyse.py: {RUN_DIR.name} (FREE counterpart) ===")
    print(f"  results = {RESULTS_DIR}")
    shim_log = install_schema_shims()
    if shim_log:
        print("  schema shims installed:")
        for line in shim_log:
            print(line)
    print(f"  phases  = {', '.join(PIPELINE_PHASES)}\n")

    res = pipeline.run(
        RESULTS_DIR,
        run_name=RUN_DIR.name,
        phases=PIPELINE_PHASES,
        rebuild=False,
        skip_paraview=True,
    )

    pipe_log: dict[str, str] = {}
    for ph in PIPELINE_PHASES:
        if ph in res.ok:        pipe_log[ph] = "[ok]"
        elif ph in res.skipped: pipe_log[ph] = f"[skip] {res.skipped[ph]}"
        elif ph in res.failed:  pipe_log[ph] = f"[fail] {res.failed[ph]}"
        else:                   pipe_log[ph] = "[not run]"

    try:
        from inqview.postprocess import density_fourier as _df
        print("\n=== density_fourier (axial n_q(t), m=1..6) ===")
        _df.run(RESULTS_DIR, run_name=RUN_DIR.name, m_max=6, dt_au=cfg_dt_au())
        pipe_log["density_fourier"] = "[ok]"
    except FileNotFoundError as exc:
        pipe_log["density_fourier"] = f"[skip] {exc}"
        print(f"\ndensity_fourier skipped: {exc}")
    except Exception as exc:
        pipe_log["density_fourier"] = f"[fail] {type(exc).__name__}: {exc}"
        print(f"\ndensity_fourier failed: {exc}")

    rs_keys = ["cell_bohr", "spacing_bohr",
               "wp_energy_ev", "wp_sigma_bohr", "wp_k0_bohr_inv",
               "wp_center_bohr", "wp_state_index", "norm_after",
               "wall_time_s", "dt_au", "rt_num_steps"]
    rs = {k: read_summary_value(SUMMARY, k, "?") for k in rs_keys}
    phys = physics_block()

    out_md = ANALYSIS / "REPORT.md"
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(render_markdown(phys, rs, pipe_log))
    print(f"\nWrote {out_md}\n")

    print("=== Physics summary ===")
    print(f"  ΔE_total      : {phys['dE_total_eV']*1e6:+.4f} μeV (conservation residual)")
    print(f"  ΔE_kinetic    : {phys['dE_kinetic_eV']:+.4f} eV")
    print(f"  ΔE_hartree    : {phys['dE_hartree_eV']:+.4f} eV  (expect 0 — non-interacting)")
    print(f"  ΔE_xc         : {phys['dE_xc_eV']:+.4f} eV  (expect 0 — non-interacting)")
    print(f"  dipole_z(0,end)= {phys['dipole_z0']:+.4f} → {phys['dipole_z1']:+.4f}  "
          f"(Δ = {phys['dipole_z_advance']:+.4f})")
    print()
    print("=== Pipeline ===")
    for ph in PIPELINE_PHASES:
        print(f"  {pipe_log[ph]:<60} {ph}")

    return 0 if not res.failed else 1


def cfg_dt_au() -> float:
    """Read dt_au from run_summary.txt for density_fourier."""
    v = read_summary_value(SUMMARY, "dt_au", 0.01)
    return float(v)


if __name__ == "__main__":
    sys.exit(main())
