#pragma once
// ============================================================================
// run_002 — Coronene TDDFT LEED simulation
// Configuration: 200 eV, d=1.4 Å, E_cut=54 Ha, centred geometry
//
// Changes from run_001:
//   - E_cut = 54 Ha  (paper grid spacing 0.16 Å; run_001 used 40 Ha)
//   - WP width d = 1.4 Å  (was 0.53 Å; now illuminates central ring properly)
//   - Geometry centred at (Lx/2, Ly/2, Lz/2) in XYZ file
//   - Z_FLAKE and Z_OBS updated to reflect centred geometry
//   - Extra observables: energy CSV, projected occupation CSV, WP orbital slices
//
// Source: Tsubonoya, Hu, Watanabe, PRB 90, 035416 (2014)
// All values in atomic units unless annotated.
// ============================================================================

#include <inq/inq.hpp>
#include <cmath>

namespace cfg {

using namespace inq::magnitude;

// ── Unit conversions ─────────────────────────────────────────────────────────
inline constexpr double ANG_TO_BOHR  = 1.8897259886;
inline constexpr double BOHR_TO_ANG  = 0.529177210903;
inline constexpr double HA_TO_EV     = 27.21138625;
inline constexpr double FS_TO_AU     = 1.0 / 0.024188843;

// ── Cell dimensions ──────────────────────────────────────────────────────────
// Finite (isolated molecule), same as paper: 18.4 × 18.4 × 31.7 Å
inline constexpr double LX_ANG  = 18.4;
inline constexpr double LY_ANG  = 18.4;
inline constexpr double LZ_ANG  = 31.7;

inline constexpr double LX_BOHR = LX_ANG * ANG_TO_BOHR;  // 34.771 bohr
inline constexpr double LY_BOHR = LY_ANG * ANG_TO_BOHR;  // 34.771 bohr
inline constexpr double LZ_BOHR = LZ_ANG * ANG_TO_BOHR;  // 59.904 bohr

inline auto make_cell() {
    return inq::systems::cell::orthorhombic(
        LX_BOHR*1.0_b, LY_BOHR*1.0_b, LZ_BOHR*1.0_b).finite();
}

// ── Coronene geometry ─────────────────────────────────────────────────────────
// Centred at (Lx/2, Ly/2, Lz/2) Å — all atoms have positive coordinates
// within the cell. Generated by run_002/coronene_centered.xyz.
inline constexpr const char* CORONENE_XYZ = "coronene_centered.xyz";

// ── Electronic structure ─────────────────────────────────────────────────────
// 24×C(4e) + 12×H(1e) = 108 electrons → 54 occupied KS orbitals
inline constexpr int EXTRA_STATES = 3;   // 1 WP slot + 2 SCF buffer

// E_cut = 40 Ha → grid spacing h = π/√(2×40) = 0.351 bohr = 0.186 Å
// Chosen as the energy minimum from the 03_ecut_convergence sweep.
// 54 Ha matches the paper grid spacing but causes pseudodojo_pbe projector
// completeness artefacts above ~40 Ha, leading to oscillatory SCF convergence.
inline constexpr double ECUT_HA_LEED = 40.0;   // Ha

// SCF tolerance
// 1e-4 Ha: sufficient for TDDFT initial conditions. The Broyden mixer
// stagnates below ~1e-5 Ha with the centred geometry; 1e-4 Ha is well within
// the regime where KS eigenvalues and orbitals are stable for propagation.
inline constexpr double SCF_TOL = 1.0e-4;  // Ha

// ── Wavepacket parameters ─────────────────────────────────────────────────────
// Paper Eq. 1: ψ^WP = (1/(πd²))^{3/4} exp(−|r−b|²/(2d²)) exp(ik·r)
//
// d = 1.4 Å: at the central ring (r=1.421 Å), density is 35.7% of peak.
//            at the middle ring  (r=2.842 Å), density is  1.6% of peak.
// This is a good compromise to illuminate the full central hexagon.
inline constexpr double WP_D_ANG  = 1.4;
inline constexpr double WP_D_BOHR = WP_D_ANG * ANG_TO_BOHR;  // 2.6456 bohr

// Impact distance D = 6.35 Å (paper value)
inline constexpr double WP_D_IMPACT_ANG  = 6.35;
inline constexpr double WP_D_IMPACT_BOHR = WP_D_IMPACT_ANG * ANG_TO_BOHR;  // 12.000 bohr

// Kinetic energy 200 eV
inline constexpr double WP_EKIN_EV = 200.0;
inline constexpr double WP_EKIN_HA = WP_EKIN_EV / HA_TO_EV;   // 7.3499 Ha

// k₀ = √(2 E_kin)   (atomic units: m=1, ℏ=1)
inline double wp_k0()  { return std::sqrt(2.0 * WP_EKIN_HA); }  // 3.834 bohr⁻¹

// Normalisation (1/(π d²))^{3/4}
inline double wp_norm(){ return std::pow(M_PI * WP_D_BOHR * WP_D_BOHR, -0.75); }

// WP centre in cell coordinates (centred geometry)
// bx = Lx/2, by = Ly/2, bz = Lz/2 + D  (above the molecule, in +z direction)
inline double WP_BX() { return LX_BOHR / 2.0; }
inline double WP_BY() { return LY_BOHR / 2.0; }
inline double WP_BZ() { return LZ_BOHR / 2.0 + WP_D_IMPACT_BOHR; }  // 41.952 bohr

inline constexpr double WP_OCCUPATION = 1.0;  // singly occupied incident electron

// ── Observation and snapshot planes ──────────────────────────────────────────
// Coronene plane: z = Lz/2 (molecule centred in z)
inline double Z_FLAKE_BOHR() { return LZ_BOHR / 2.0; }         // 29.952 bohr

// Observation plane: z = Lz/2 + D (incident side, where WP starts)
inline double Z_OBS_BOHR()   { return LZ_BOHR / 2.0 + WP_D_IMPACT_BOHR; }  // 41.952 bohr

// ── TDDFT propagation parameters ─────────────────────────────────────────────
// Paper: Δt = 4.84×10⁻⁴ fs, t₂ = 0.25 fs
inline constexpr double DT_FS  = 4.84e-4;                        // fs
inline constexpr double DT_AU  = DT_FS * FS_TO_AU;               // 0.020009 a.u.

inline constexpr double T2_FS  = 0.25;
inline constexpr double T2_AU  = T2_FS * FS_TO_AU;               // 10.335 a.u.

// LEED accumulation window: t₁ = 0.077 fs to t₂ = 0.25 fs
// At t₁: WP centre z(t₁) = Lz/2 + D - k₀×t₁ ≈ Lz/2  (WP at molecule plane)
inline constexpr double T1_FS  = 0.077;
inline constexpr double T1_AU  = T1_FS * FS_TO_AU;               // 3.183 a.u.

inline constexpr int N_STEPS   = static_cast<int>(T2_AU / DT_AU); // 516 steps

// Snapshot and observable save intervals
inline constexpr int SNAPSHOT_INTERVAL = 25;   // density/orbital snapshots (every 25 steps)
inline constexpr int OVERLAP_INTERVAL  = 5;    // projected occupation save interval
inline constexpr int MAX_SNAPSHOTS     = 25;

} // namespace cfg
