#pragma once
// ============================================================================
// config.hpp — Shared configuration for coronene WP scattering simulations
//
// Source: Tsubonoya, Hu, Watanabe, PRB 90, 035416 (2014)
//   DOI: 10.1103/PhysRevB.90.035416
//
// All values in atomic units unless annotated otherwise.
// ============================================================================

#include <inq/inq.hpp>
#include <cmath>

namespace cfg {

using namespace inq::magnitude;

// ── Cell dimensions (paper: 18.4 × 18.4 × 31.7 Å) ─────────────────────────
// Finite (isolated) cell; coronene in the xy-plane at z=0.
inline constexpr double LX_ANG  = 18.4;   // Angstrom
inline constexpr double LY_ANG  = 18.4;
inline constexpr double LZ_ANG  = 31.7;

inline constexpr double LX_BOHR = LX_ANG * 1.8897259886;   // 34.76 bohr
inline constexpr double LY_BOHR = LY_ANG * 1.8897259886;   // 34.76 bohr
inline constexpr double LZ_BOHR = LZ_ANG * 1.8897259886;   // 59.91 bohr

inline auto make_cell() {
    return inq::systems::cell::orthorhombic(LX_BOHR*1.0_b, LY_BOHR*1.0_b, LZ_BOHR*1.0_b).finite();
}

// ── Coronene geometry ────────────────────────────────────────────────────────
// XYZ file path (relative to simulation directory, or absolute).
// Positions are in Angstrom, centred at origin; INQ places them within the finite cell.
// Generated by 01_geometry/gen_geometry.py (verified: 30 C-C + 12 C-H bonds).
inline constexpr const char* CORONENE_XYZ = "../01_geometry/coronene.xyz";

// ── Electronic structure ─────────────────────────────────────────────────────
// Coronene valence electrons: 24×C(4e) + 12×H(1e) = 108 → 54 occupied orbitals
// extra_states: 1 for WP orbital + 2 SCF buffer = 3 total
inline constexpr int EXTRA_STATES = 3;

// Energy cutoff (initial value; refine with 03_ecut_convergence).
// Paper grid: 0.16 Å spacing → E_cut ≈ (π/0.3024_bohr)²/2 ≈ 54 Ha
// Starting with 30 Ha; update after convergence test.
inline constexpr double ECUT_HA  = 30.0;   // Ha  — update after convergence test

// SCF tolerance
inline constexpr double SCF_TOL  = 1.0e-6; // Ha

// XC: LDA (ALDA in real-time = adiabatic LDA; paper uses ALDA)
// In INQ: options::theory{}.lda()

// ── Wavepacket parameters (paper Eq. 1) ──────────────────────────────────────
// ψ^WP(r) = (1/(π d²))^{3/4} · exp(−|r−b|²/(2d²)) · exp(i k·r)
//
inline constexpr double WP_D_ANG  = 0.53;                              // Å, WP width
inline constexpr double WP_D_BOHR = WP_D_ANG * 1.8897259886;          // 1.001 bohr
inline constexpr double WP_D_IMPACT_ANG  = 6.35;                       // Å, impact distance
inline constexpr double WP_D_IMPACT_BOHR = WP_D_IMPACT_ANG * 1.8897259886; // 12.0 bohr

// Kinetic energy: 200 eV = 7.350 Ha (1 Ha = 27.2114 eV)
inline constexpr double WP_EKIN_EV   = 200.0;
inline constexpr double WP_EKIN_HA   = WP_EKIN_EV / 27.21138625;      // 7.3499 Ha

// Momentum: k₀ = sqrt(2 E_kin) in a.u.  (E = k²/2, m=1)
inline double wp_k0() { return std::sqrt(2.0 * WP_EKIN_HA); }          // ≈ 3.832 bohr⁻¹

// Normalisation: N = (π d²)^{-3/4}  (ensures ⟨ψ|ψ⟩ = 1)
inline double wp_norm() {
    return std::pow(M_PI * WP_D_BOHR * WP_D_BOHR, -0.75);
}

// WP occupation: 1 (one incident electron; singly occupied)
inline constexpr double WP_OCCUPATION = 1.0;

// ── TDDFT propagation (LEED mode) ────────────────────────────────────────────
// Paper: Δt = 4.84×10⁻⁴ fs; total time t₂ = 0.25 fs
// 1 a.u. time = 0.024189 fs
inline constexpr double DT_FS     = 4.84e-4;                          // fs
inline constexpr double DT_AU     = DT_FS / 0.024188843;              // ≈ 0.02 a.u.
inline constexpr double T2_FS     = 0.25;                             // fs  (end time)
inline constexpr double T2_AU     = T2_FS / 0.024188843;              // ≈ 10.33 a.u.
inline constexpr int    N_STEPS   = static_cast<int>(T2_AU / DT_AU);  // ≈ 517

// t₁: WP arrival time = D / v = D / k₀ (a.u.)
inline double t1_au() { return WP_D_IMPACT_BOHR / wp_k0(); }          // ≈ 3.13 a.u.

// Observation plane for LEED: z = +D (same as initial WP position)
// Paper: "observation plane is set at the incident position"
inline constexpr double Z_OBS_BOHR = WP_D_IMPACT_BOHR;               // 12.0 bohr

// Density snapshot interval (every N steps)
inline constexpr int SNAPSHOT_INTERVAL = 50;

// ── Utility: unit conversions ─────────────────────────────────────────────
inline constexpr double ANG_TO_BOHR  = 1.8897259886;
inline constexpr double HA_TO_EV     = 27.21138625;
inline constexpr double FS_TO_AU     = 1.0 / 0.024188843;

} // namespace cfg
