#!/usr/bin/env python3
"""Shared notebook-builder helpers for the localised jellium study notebooks.

House-narrative builders (per ADR 0007 + the `notebook-making` skill) import this
to emit `nbformat` cells and execute them in the venv kernel, so the committed
`.ipynb` carries its own outputs. Run a builder with the venv interpreter:

    PYTHONPATH=/local/data/public/skcb2/tddft/inq-stack/python \
    /local/data/public/skcb2/tddft/venv/bin/python3 build_<name>_report.py

All figures/GIFs are pre-generated by the per-phase post-processing scripts; the
builders only *embed* them (PNG/GIF) and recompute headline numbers from the run
provenance CSVs so a figure and its quoted number can never disagree.
"""
import copy
import os
import re
import nbformat as nbf
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
from nbconvert.preprocessors import ExecutePreprocessor

REPO = "/local/data/public/skcb2/tddft"
STACK = f"{REPO}/inq-stack/python"
SYS = f"{REPO}/ResearchProject/systems/localised_jellium"


# ---- annotation preservation (harvest-before-rebuild) ----------------------
# Builder cells carry metadata.gen="builder" (+ anchor slug for headed markdown).
# A rebuild harvests reader markdown (untagged) and re-injects it at the anchor so
# annotations added directly in Jupyter survive. See notebook-making SKILL.md.
def slug(text):
    line = text.strip().splitlines()[0] if text.strip() else ""
    line = re.sub(r"^#+\s*", "", line)
    line = re.sub(r"[`*_$\\(){}\[\]]", "", line)
    return re.sub(r"[^a-z0-9]+", "-", line.lower()).strip("-")[:60]


def tag_builder(cell):
    cell.setdefault("metadata", {})["gen"] = "builder"
    src = cell.get("source", "")
    if cell.get("cell_type") == "markdown" and src.lstrip().startswith("#"):
        cell["metadata"]["anchor"] = slug(src)
    return cell


def harvest_user_cells(ipynb_path):
    """{anchor -> [user markdown/raw cell]} from an EXISTING notebook (untagged
    markdown = reader-authored). Empty if absent."""
    if not os.path.exists(ipynb_path):
        return {}
    try:
        nb = nbf.read(ipynb_path, as_version=4)
    except Exception:
        return {}
    # Transition guard: pre-tagging notebooks have no gen='builder' cells.
    if not any(c.get("metadata", {}).get("gen") == "builder" for c in nb.cells):
        return {}
    out, cur = {}, "__orphan__"
    for c in nb.cells:
        is_builder = c.get("metadata", {}).get("gen") == "builder"
        if c.cell_type == "markdown" and is_builder:
            cur = c.get("metadata", {}).get("anchor", cur)
        elif c.cell_type in ("markdown", "raw") and not is_builder:
            out.setdefault(cur, []).append(c)
    return out


def reinject(cells, harvested):
    """Splice harvested reader cells after their anchor; orphans → carried-over
    section after the title. Never drops annotations."""
    if not harvested:
        return cells
    out, used = [], set()
    for c in cells:
        out.append(c)
        a = c.get("metadata", {}).get("anchor")
        if a and a in harvested:
            for uc in harvested[a]:
                u = copy.deepcopy(uc); u.setdefault("metadata", {})["gen"] = "user"
                out.append(u)
            used.add(a)
    leftover = [uc for a, ucs in harvested.items() if a not in used for uc in ucs]
    if leftover:
        hdr = tag_builder(new_markdown_cell(
            "## 📌 Carried-over reader annotations (original section changed/removed)"))
        block = [hdr]
        for x in leftover:
            u = copy.deepcopy(x); u.setdefault("metadata", {})["gen"] = "user"
            block.append(u)
        out = out[:1] + block + out[1:]
    return out


def md(text):
    return tag_builder(new_markdown_cell(text))


def code(src):
    return tag_builder(new_code_cell(src))


def setup_cell():
    """First code cell: put inqview on the path and apply the canonical theme."""
    return code(
        "import sys, os\n"
        f"sys.path.insert(0, {STACK!r})\n"
        "import numpy as np\n"
        "from IPython.display import Image, display\n"
        "from inqview.visualisation import style\n"
        "style.apply_theme()\n"
        f"SYS = {SYS!r}\n"
        "print('theme applied; provenance root:', SYS)"
    )


_OUTDIR = None


def set_outdir(d):
    """Set the notebook's folder so embed() can emit RELATIVE figure paths."""
    global _OUTDIR
    _OUTDIR = d


def embed(path, caption=None, width=None):
    """Markdown cell referencing a PNG/GIF by RELATIVE path (NOT base64-embedded),
    so the .ipynb stays small and viewers render it. The figure must travel beside
    the notebook (figures live in the notebook's folder / subfolders).

    ``width`` (px) caps the on-screen display size via an HTML ``<img>`` tag —
    Markdown ``![]()`` renders at native pixel size, which is too large for the
    GIF battery. ``width=None`` keeps the plain Markdown form (back-compat)."""
    rel = os.path.relpath(path, _OUTDIR) if _OUTDIR else os.path.basename(path)
    cap = caption or ""
    if width is not None:
        img = f'<img src="{rel}" width="{int(width)}" alt="{cap}">'
        return md(f"*{cap}*\n\n{img}" if cap else img)
    return md(f"*{cap}*\n\n![{cap}]({rel})" if cap else f"![]({rel})")


def build(cells, out_path, timeout=600):
    """Assemble, execute in the venv kernel, and write the executed notebook.
    Preserves reader annotations: harvests untagged markdown from the existing
    notebook and re-injects it; pins a `<stem>.notes.md` sidecar as a top cell."""
    harvested = harvest_user_cells(out_path)
    # sidecar notes pin (after the title cell)
    notes = os.path.splitext(out_path)[0] + ".notes.md"
    if os.path.exists(notes):
        body = open(notes).read().strip()
        if body:
            ncell = tag_builder(new_markdown_cell(
                f"## 📝 Reader notes / TODOs\n*(pinned from `{os.path.basename(notes)}` — "
                f"edit that file; regenerated each build, never overwritten.)*\n\n{body}"))
            cells = ([cells[0], ncell] + cells[1:]) if cells else [ncell]
    cells = reinject(cells, harvested)
    nb = new_notebook(cells=cells)
    nb.metadata["kernelspec"] = {
        "name": "python3", "display_name": "Python 3", "language": "python"}
    ep = ExecutePreprocessor(timeout=timeout, kernel_name="python3")
    ep.preprocess(nb, {"metadata": {"path": os.path.dirname(out_path)}})
    with open(out_path, "w") as f:
        nbf.write(nb, f)
    n_user = sum(1 for c in nb.cells if c.get("metadata", {}).get("gen") == "user")
    print(f"wrote + executed: {out_path}  ({n_user} reader annotation(s) preserved)")
    return out_path
