#!/usr/bin/env python3
"""analyse.py — per-run postprocess for run_classical_n162_L50_E100.

Self-contained: invokes the inqview postprocess pipeline with EVERY phase
relevant to a classical-electron jellium TDDFT run, computes the physics
summary (stopping power, energy budget, conservation), and writes a
markdown REPORT.md plus all the standard plots/CSVs/GIFs into
results/analysis/observables/.

Usage:
    cd <this dir>
    python3 analyse.py

The pipeline phases run here are everything except `screens` (no LEED
screens in this run) and `paraview` / `paraview_3d` (rendering is
on-demand). Specifically:

    summary, gs, layout, observables, eigenvalues_gs, state_energies,
    state_energy_spectra, bath_energy, stopping, gs_projected_occupations,
    occupations, momentum, density, overlap, orbitals

For a wave-packet companion run, see run_wp_n162_L50_E100/analyse.py.
"""
from __future__ import annotations

import os
import re
import sys
import textwrap
from pathlib import Path

import numpy as np
import pandas as pd

HA_TO_EV = 27.211386245988
M_E_AU   = 1.0

RUN_DIR     = Path(__file__).resolve().parent
RESULTS_DIR = RUN_DIR / "results"
ANALYSIS    = RESULTS_DIR / "analysis"
SUMMARY     = RESULTS_DIR / "run_summary.txt"

# All phases relevant to a CLASSICAL-electron jellium TDDFT run.
# `screens` is skipped (no LEED screens captured); `paraview*` is on-demand.
PIPELINE_PHASES: tuple[str, ...] = (
    "summary",
    "gs",
    "layout",
    "observables",
    "eigenvalues_gs",
    "state_energies",
    "state_energy_spectra",
    "bath_energy",
    "stopping",
    "gs_projected_occupations",
    "occupations",
    "momentum",
    "density",
    "overlap",
    "orbitals",
)


def read_summary_value(path: Path, key: str, default=None):
    if not path.exists():
        return default
    m = re.search(rf"^\s*{re.escape(key)}\s*=\s*(\S+)",
                  path.read_text(), flags=re.MULTILINE)
    if not m:
        return default
    s = m.group(1)
    try:
        return float(s)
    except ValueError:
        return s


def physics_block() -> dict:
    obs_dir = RESULTS_DIR / "raw" / "observables"
    obs   = pd.read_csv(obs_dir / "observables.csv")
    track = pd.read_csv(obs_dir / "electron_track.csv")

    z0, z1 = float(track["z"].iloc[0]), float(track["z"].iloc[-1])
    v0, v1 = float(track["vz"].iloc[0]), float(track["vz"].iloc[-1])
    KE0 = 0.5 * M_E_AU * v0 ** 2
    KE1 = 0.5 * M_E_AU * v1 ** 2

    cE0  = float(obs["energy_total"].iloc[0])
    cE1  = float(obs["energy_total"].iloc[-1])
    cEk0, cEk1 = float(obs["energy_kinetic"].iloc[0]), float(obs["energy_kinetic"].iloc[-1])
    cEh0, cEh1 = float(obs["energy_hartree"].iloc[0]), float(obs["energy_hartree"].iloc[-1])
    cEx0, cEx1 = float(obs["energy_xc"].iloc[0]),     float(obs["energy_xc"].iloc[-1])

    distance     = z1 - z0
    KE_loss_eV   = (KE0 - KE1) * HA_TO_EV
    bath_gain_eV = (cE1 - cE0) * HA_TO_EV
    S            = (KE0 - KE1) / distance * HA_TO_EV if abs(distance) > 1e-9 else float("nan")

    return {
        "z0": z0, "z1": z1, "distance_Bohr": distance,
        "v0": v0, "v1": v1,
        "KE0_eV": KE0 * HA_TO_EV, "KE1_eV": KE1 * HA_TO_EV,
        "KE_loss_eV":   KE_loss_eV,
        "S_eV_per_Bohr": S,
        "dE_total_eV":   bath_gain_eV,
        "dE_kinetic_eV": (cEk1 - cEk0) * HA_TO_EV,
        "dE_hartree_eV": (cEh1 - cEh0) * HA_TO_EV,
        "dE_xc_eV":      (cEx1 - cEx0) * HA_TO_EV,
        "energy_conservation_residual_eV": bath_gain_eV - KE_loss_eV,
        "n_frames":      len(obs),
        "total_time_au": float(obs["time_au"].iloc[-1]),
    }


def render_markdown(phys: dict, rs: dict, pipe_log: dict) -> str:
    md = f"""# Analysis: {RUN_DIR.name}

Auto-generated by `{Path(__file__).name}`. Re-run any time after
modifying observables to refresh plots.

## Run identity

| Field | Value |
|---|---|
| Run dir | `{RUN_DIR}` |
| Cell | {rs.get('cell_bohr', '?')} (cubic, periodic) |
| N_electrons | {rs.get('n_electrons', '?')} |
| Spacing | {rs.get('spacing_bohr', '?')} Bohr |
| Projectile KE | {rs.get('projectile_KE_eV', '?')} eV |
| Initial v_z | {rs.get('velocity_atu', '?')} bohr/atu |
| Ion dynamics | {rs.get('ion_dynamics', '?')} |
| dt × N_steps | {rs.get('dt_au','?')} × {rs.get('rt_num_steps','?')} (= {phys['total_time_au']:.3f} a.u.) |
| Wall time | {rs.get('wall_time_s', '?')} s |

## Trajectory

| Quantity | Value |
|---|---|
| z(t=0)            | {phys['z0']:+.4f} Bohr (INQ centred) |
| z(t=end)          | {phys['z1']:+.4f} Bohr |
| Distance traveled | {phys['distance_Bohr']:.4f} Bohr |
| v_z(t=0)          | {phys['v0']:.6f} bohr/atu |
| v_z(t=end)        | {phys['v1']:.6f} bohr/atu |
| Velocity drop     | {phys['v0']-phys['v1']:+.6f} bohr/atu ({100*(phys['v0']-phys['v1'])/phys['v0']:+.4f} %) |
| KE(t=0)           | {phys['KE0_eV']:.4f} eV |
| KE(t=end)         | {phys['KE1_eV']:.4f} eV |
| **KE loss**       | **{phys['KE_loss_eV']:+.4f} eV** |
| **Stopping power S(v)** | **{phys['S_eV_per_Bohr']:.4f} eV / Bohr** |

## Energy budget (electronic, end − start)

| Term | Value |
|---|---|
| Δ E_total       | {phys['dE_total_eV']:+.4f} eV (≈ bath gain from `.ehrenfest()`) |
| Δ E_kinetic     | {phys['dE_kinetic_eV']:+.4f} eV |
| Δ E_hartree     | {phys['dE_hartree_eV']:+.4f} eV |
| Δ E_xc          | {phys['dE_xc_eV']:+.4f} eV |
| Conservation residual = bath_gain − KE_loss | {phys['energy_conservation_residual_eV']:+.4f} eV |

## Postprocess pipeline outcome

"""
    for ph in PIPELINE_PHASES:
        flag = pipe_log.get(ph, "skip")
        md += f"- **{ph}**: {flag}\n"
    md += textwrap.dedent(f"""
## Output layout

```
results/analysis/observables/
├── observables_summary.png
├── total_energy_vs_time.png
├── all_energies_vs_time.png
├── current_components_vs_time.png
├── dipole_components_vs_time.png
├── density_fluctuation_l2.png         (if density-delta produced)
├── fft_total_energy.png, fft_current_*.png, dipole_spectrum_*.png
├── dE_kinetic_vs_z.png                (stopping curve)
├── stopping_force_vs_z.png            (F_z = m dv/dt from electron_track)
├── bath_energy_vs_time.png, bath_energy_vs_time.csv
├── ks_energies_absolute.gif, ks_energies_delta.gif
├── occupations_absolute.gif, occupations_delta.gif
├── momentum_distribution.gif, momentum_heatmap.png
└── gs_projected_occupations/
    ├── n_i_gs_vs_time.csv
    ├── excitation_total_vs_time.{{csv,png}}
    ├── gs_projection_t<NN>.png
    └── heatmap_overlap_t<NN>.png
```

## Source data

```
results/raw/observables/
├── observables.csv             ({phys['n_frames']} rows)
├── electron_track.csv          (per-step projectile r/v)
├── state_energies.csv          (per-orbital E_i(t))
├── occupations_vs_time.csv     (per-orbital f_i(t))
├── momentum_distribution.csv   (n(|k|, t))
├── overlap_full/               (full O matrix at t=0, mid, end)
├── overlap_proxies/            (proxy O matrix every PROXY_SNAPSHOT_STRIDE)
└── eigenvalues/                (GS eigenvalues + occupations)
```
""")
    return md


def install_schema_shims() -> list[str]:
    """Bridge two long-standing path-schema mismatches so the pipeline's
    `overlap` and `density_fourier` phases find our data.

    Our run.cpp writes:
      results/raw/observables/overlap{,_full,_proxies}/
      results/raw/vti/density_{total,system,delta,delta_coarse}/

    But inqview's overlap phase expects results/raw/overlap/, and
    density_fourier expects raw/vti/density_rt_total/. We add symlinks
    (idempotent) rather than rewrite the C++ — same data, both layouts
    discoverable.
    """
    log: list[str] = []
    pairs = [
        (RESULTS_DIR / "raw" / "overlap",
         RESULTS_DIR / "raw" / "observables" / "overlap"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_total",
         RESULTS_DIR / "raw" / "vti" / "density_total"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_system",
         RESULTS_DIR / "raw" / "vti" / "density_system"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta",
         RESULTS_DIR / "raw" / "vti" / "density_delta"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta_coarse",
         RESULTS_DIR / "raw" / "vti" / "density_delta_coarse"),
    ]
    for link, target in pairs:
        if link.exists() or link.is_symlink():
            continue
        if not target.exists():
            continue
        # Use absolute target so the symlink survives if cwd changes.
        link.parent.mkdir(parents=True, exist_ok=True)
        link.symlink_to(target.resolve())
        log.append(f"  symlink {link.name} → {target.name}")
    return log


def main() -> int:
    if not RESULTS_DIR.exists():
        print(f"FATAL: {RESULTS_DIR} does not exist", file=sys.stderr)
        return 2

    # Make sure inqview is importable. Add inq-stack/python to sys.path if
    # the venv isn't activated.
    try:
        from inqview.pipeline import runner as pipeline  # noqa: F401
    except ImportError:
        sys.path.insert(0, "/local/data/public/skcb2/tddft/inq-stack/python")
        from inqview.pipeline import runner as pipeline  # noqa: F401

    print(f"=== analyse.py: {RUN_DIR.name} ===")
    print(f"  results = {RESULTS_DIR}")
    shim_log = install_schema_shims()
    if shim_log:
        print("  schema shims installed:")
        for line in shim_log:
            print(line)
    print(f"  phases  = {', '.join(PIPELINE_PHASES)}\n")

    res = pipeline.run(
        RESULTS_DIR,
        run_name=RUN_DIR.name,
        phases=PIPELINE_PHASES,
        rebuild=False,
        skip_paraview=True,
    )

    pipe_log: dict[str, str] = {}
    for ph in PIPELINE_PHASES:
        if ph in res.ok:      pipe_log[ph] = "[ok]"
        elif ph in res.skipped: pipe_log[ph] = f"[skip] {res.skipped[ph]}"
        elif ph in res.failed:  pipe_log[ph] = f"[fail] {res.failed[ph]}"
        else:                   pipe_log[ph] = "[not run]"

    # density_fourier is not in pipeline._PHASE_FUNCS; call it directly.
    # Useful even for the classical run: detects any coherent
    # density-fluctuation modes (plasmon-like) excited by the moving ion.
    try:
        from inqview.pipeline import density_fourier as _df
        print("\n=== density_fourier (axial n_q(t), m=1..6) ===")
        _df.run(RESULTS_DIR, run_name=RUN_DIR.name, m_max=6, dt_au=0.02)
        pipe_log["density_fourier"] = "[ok]"
    except FileNotFoundError as exc:
        pipe_log["density_fourier"] = f"[skip] {exc}"
        print(f"\ndensity_fourier skipped: {exc}")
    except Exception as exc:
        pipe_log["density_fourier"] = f"[fail] {type(exc).__name__}: {exc}"
        print(f"\ndensity_fourier failed: {exc}")

    # ---- Custom post-pipeline analyses ----
    # Force fix (eV/Bohr from dv/dt), bath excess energy vs time + vs z
    # (slope = stopping power), overlap heatmap |O_ij(t_end)|², and
    # effective GS-projected occupations n_i^GS(t_end) = Σ_j f_j |O_ij|².
    sys.path.insert(0, str(RUN_DIR.parent / "shared" / "python"))
    from analyse_extras import run_extras
    print("\n=== custom analyses (analyse_extras) ===")
    extras_log = run_extras(RESULTS_DIR, RUN_DIR.name, is_classical=True)
    for k, v in extras_log.items():
        pipe_log[k] = v
        print(f"  {v:<70} {k}")

    # Read run_summary.txt for metadata.
    rs_keys = ["cell_bohr", "n_electrons", "spacing_bohr",
               "projectile_KE_eV", "velocity_atu", "ion_dynamics",
               "wall_time_s", "dt_au", "rt_num_steps"]
    rs = {k: read_summary_value(SUMMARY, k, "?") for k in rs_keys}

    # Physics summary.
    phys = physics_block()

    # Render and write the markdown report.
    out_md = ANALYSIS / "REPORT.md"
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(render_markdown(phys, rs, pipe_log))
    print(f"\nWrote {out_md}\n")

    # Stdout summary.
    print("=== Physics summary ===")
    print(f"  Distance traveled  : {phys['distance_Bohr']:+.4f} Bohr")
    print(f"  v_z drop           : {phys['v0']-phys['v1']:+.6f} bohr/atu "
          f"({100*(phys['v0']-phys['v1'])/phys['v0']:+.4f} %)")
    print(f"  KE loss            : {phys['KE_loss_eV']:+.4f} eV")
    print(f"  Stopping power S(v): {phys['S_eV_per_Bohr']:.6f} eV/Bohr")
    print(f"  ΔE_total           : {phys['dE_total_eV']:+.4f} eV")
    print(f"  ΔE_hartree         : {phys['dE_hartree_eV']:+.4f} eV")
    print(f"  ΔE_xc              : {phys['dE_xc_eV']:+.4f} eV")
    print(f"  Conservation       : {phys['energy_conservation_residual_eV']:+.4f} eV (expect ~0)")
    print()
    print("=== Pipeline ===")
    for ph in PIPELINE_PHASES:
        print(f"  {pipe_log[ph]:<60} {ph}")

    return 0 if not res.failed else 1


if __name__ == "__main__":
    sys.exit(main())
