#!/usr/bin/env python3
"""Regenerate docs/campaigns/INDEX.md from campaign frontmatter.

Skill-local generator for the `campaigns` skill (kept inside the skill folder so
the skill ships self-contained). Stdlib only — no PyYAML — because it parses one
fixed schema we control (see docs/campaigns/template.md), not arbitrary YAML.

Usage:
    python3 build_index.py <campaigns_dir>     # writes <campaigns_dir>/INDEX.md

A "campaign" is any .md under <campaigns_dir> whose YAML frontmatter carries an
`id`. INDEX.md and template.md (and any file without an `id`) are skipped.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

# Display order + label for each status group. Files float up by activity.
STATUS_ORDER = ["running", "blocked", "paused", "ready", "draft", "done"]
STATUS_LABEL = {
    "running": "🟢 Running",
    "blocked": "⛔ Blocked",
    "paused": "⏸️ Paused",
    "ready": "🟡 Ready",
    "draft": "⚪ Draft",
    "done": "✅ Done",
}

FM_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)


def _strip(v: str) -> str:
    """Drop surrounding quotes and whitespace from a scalar value."""
    v = v.strip()
    if len(v) >= 2 and v[0] in "\"'" and v[-1] == v[0]:
        v = v[1:-1]
    return v


def parse_frontmatter(text: str) -> dict | None:
    """Parse the constrained campaign frontmatter. Returns None if absent.

    Handles top-level `key: value` scalars plus a `tasks:` list written either
    flow-style (`- { name: "x", done: false }`) or block-style
    (`- name: "x"` / `  done: false`). Anything else is ignored.
    """
    m = FM_RE.match(text)
    if not m:
        return None
    body = m.group(1)
    data: dict = {}
    tasks: list[dict] = []
    in_tasks = False
    cur: dict | None = None

    for raw in body.splitlines():
        if not raw.strip() or raw.lstrip().startswith("#"):
            continue
        indented = raw[0] in (" ", "\t")
        stripped = raw.strip()

        # A top-level key ends any tasks block.
        if not indented and ":" in stripped and not stripped.startswith("-"):
            key, _, val = stripped.partition(":")
            key = key.strip()
            if key == "tasks":
                in_tasks = True
                cur = None
                continue
            in_tasks = False
            data[key] = _strip(val)
            continue

        if not in_tasks:
            continue

        # Within tasks:
        if stripped.startswith("-"):
            item = stripped[1:].strip()
            if item.startswith("{") and item.endswith("}"):  # flow style
                inner = item[1:-1]
                td: dict = {}
                for part in re.split(r",(?![^()]*\))", inner):
                    if ":" in part:
                        k, _, v = part.partition(":")
                        td[k.strip()] = _strip(v)
                tasks.append(td)
                cur = None
            else:  # block style, first key on the dash line
                cur = {}
                tasks.append(cur)
                if ":" in item:
                    k, _, v = item.partition(":")
                    cur[k.strip()] = _strip(v)
        elif cur is not None and ":" in stripped:  # continuation of block item
            k, _, v = stripped.partition(":")
            cur[k.strip()] = _strip(v)

    data["tasks"] = tasks
    return data


def _is_done(task: dict) -> bool:
    return str(task.get("done", "")).strip().lower() == "true"


def collect(campaigns_dir: Path) -> list[dict]:
    out = []
    for path in sorted(campaigns_dir.rglob("*.md")):
        if path.name in ("INDEX.md", "template.md"):
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        if not fm or "id" not in fm:
            continue
        tasks = fm.get("tasks", [])
        fm["_done"] = sum(_is_done(t) for t in tasks)
        fm["_total"] = len(tasks)
        fm["_rel"] = path.relative_to(campaigns_dir).as_posix()
        out.append(fm)
    return out


def _handover_link(h: str) -> str:
    h = (h or "").strip()
    if not h:
        return "—"
    # INDEX.md lives in docs/campaigns/; rewrite a repo-relative docs/ path.
    rel = ("../" + h[len("docs/"):]) if h.startswith("docs/") else h
    return f"[↗]({rel})"


def render(campaigns: list[dict]) -> str:
    counts = {s: 0 for s in STATUS_ORDER}
    for c in campaigns:
        st = (c.get("status") or "draft").strip().lower()
        counts[st] = counts.get(st, 0) + 1

    portfolio = " · ".join(
        f"{counts[s]} {s}" for s in STATUS_ORDER if counts.get(s)
    ) or "none"

    lines = [
        "# Campaign INDEX",
        "",
        "> Auto-generated by the `campaigns` skill "
        "(`.claude/skills/campaigns/build_index.py`).",
        "> **Do NOT hand-edit** — regenerated on every campaigns-skill run.",
        "",
        f"**Portfolio:** {portfolio}  ({len(campaigns)} campaigns)",
        "",
    ]

    for st in STATUS_ORDER:
        group = [c for c in campaigns
                 if (c.get("status") or "draft").strip().lower() == st]
        if not group:
            continue
        group.sort(key=lambda c: (c.get("area", ""), c.get("title", "")))
        lines += [f"## {STATUS_LABEL[st]}", "",
                  "| Campaign | Area | Progress | Handover |",
                  "|---|---|---|---|"]
        for c in group:
            title = c.get("title") or c.get("id", "?")
            progress = f"{c['_done']}/{c['_total']}"
            if st in ("blocked", "paused") and c.get("blocked_reason"):
                progress += f" — *{c['blocked_reason']}*"
            lines.append(
                f"| [{title}]({c['_rel']}) | {c.get('area','')} | "
                f"{progress} | {_handover_link(c.get('handover',''))} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__)
        return 2
    campaigns_dir = Path(argv[1]).resolve()
    if not campaigns_dir.is_dir():
        print(f"not a directory: {campaigns_dir}", file=sys.stderr)
        return 1
    campaigns = collect(campaigns_dir)
    out = campaigns_dir / "INDEX.md"
    out.write_text(render(campaigns), encoding="utf-8")
    print(f"wrote {out} ({len(campaigns)} campaigns)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
