#!/usr/bin/env python3
"""analyse.py — per-run postprocess for run_wp_n162_L50_E25_sigma1_v2.

Self-contained: invokes the inqview postprocess pipeline with EVERY phase
relevant to a wave-packet jellium TDDFT run, computes the physics summary
(energy budget, conservation, WP advance), and writes a markdown REPORT.md
plus all the standard plots/CSVs/GIFs into results/analysis/observables/.

Usage:
    cd <this dir>
    python3 analyse.py

The pipeline phases run here include the WP-specific `wp_trajectory` and
`gamma_transitions`; `stopping` is excluded (no classical electron_track),
and `screens`/`paraview*` are skipped (no LEED screens captured).
Specifically:

    summary, gs, layout, observables, eigenvalues_gs, gamma_transitions,
    wp_trajectory, state_energies, state_energy_spectra, occupations,
    momentum, density, overlap, orbitals

For the classical companion run, see run_classical_n162_L50_E100/analyse.py.
"""
from __future__ import annotations

import re
import sys
import textwrap
from pathlib import Path

import pandas as pd

HA_TO_EV = 27.211386245988

RUN_DIR     = Path(__file__).resolve().parent
RESULTS_DIR = RUN_DIR / "results"
ANALYSIS    = RESULTS_DIR / "analysis"
SUMMARY     = RESULTS_DIR / "run_summary.txt"

# All phases relevant to a WAVE-PACKET jellium TDDFT run.
# `stopping` skipped (no electron_track); `screens` skipped (no LEED);
# `paraview*` on-demand.
PIPELINE_PHASES: tuple[str, ...] = (
    "summary",
    "gs",
    "layout",
    "observables",
    "eigenvalues_gs",
    "gamma_transitions",
    "wp_trajectory",
    "state_energies",
    "state_energy_spectra",
    "occupations",
    "momentum",
    "knudsen_ke",
    "kl_divergence",
    "energy_balance",
    "density",
    "overlap",
    "orbitals",
)


def read_summary_value(path: Path, key: str, default=None):
    if not path.exists():
        return default
    m = re.search(rf"^\s*{re.escape(key)}\s*=\s*(\S+)",
                  path.read_text(), flags=re.MULTILINE)
    if not m:
        return default
    s = m.group(1)
    try:
        return float(s)
    except ValueError:
        return s


def physics_block() -> dict:
    obs_dir = RESULTS_DIR / "raw" / "observables"
    obs = pd.read_csv(obs_dir / "observables.csv")

    wE0  = float(obs["energy_total"].iloc[0])
    wE1  = float(obs["energy_total"].iloc[-1])
    wEk0, wEk1 = float(obs["energy_kinetic"].iloc[0]), float(obs["energy_kinetic"].iloc[-1])
    wEh0, wEh1 = float(obs["energy_hartree"].iloc[0]), float(obs["energy_hartree"].iloc[-1])
    wEx0, wEx1 = float(obs["energy_xc"].iloc[0]),     float(obs["energy_xc"].iloc[-1])

    # WP cod_z proxy: dipole_z change tracks the WP centroid advance because
    # the orthogonalised bath dipole stays nearly constant.
    has_dz = "dipole_z" in obs.columns
    dz0 = float(obs["dipole_z"].iloc[0]) if has_dz else float("nan")
    dz1 = float(obs["dipole_z"].iloc[-1]) if has_dz else float("nan")

    return {
        "dE_total_eV":   (wE1 - wE0) * HA_TO_EV,
        "dE_kinetic_eV": (wEk1 - wEk0) * HA_TO_EV,
        "dE_hartree_eV": (wEh1 - wEh0) * HA_TO_EV,
        "dE_xc_eV":      (wEx1 - wEx0) * HA_TO_EV,
        "sum_components_eV": ((wEk1-wEk0)+(wEh1-wEh0)+(wEx1-wEx0)) * HA_TO_EV,
        "dipole_z0":         dz0,
        "dipole_z1":         dz1,
        "dipole_z_advance":  dz1 - dz0,
        "n_frames":          len(obs),
        "total_time_au":     float(obs["time_au"].iloc[-1]),
    }


def render_markdown(phys: dict, rs: dict, pipe_log: dict) -> str:
    md = f"""# Analysis: {RUN_DIR.name}

Auto-generated by `{Path(__file__).name}`. Re-run any time after
modifying observables to refresh plots.

## Run identity

| Field | Value |
|---|---|
| Run dir | `{RUN_DIR}` |
| Cell | {rs.get('cell_bohr', '?')} (cubic, periodic) |
| N_electrons | {rs.get('n_electrons', '?')} |
| Spacing | {rs.get('spacing_bohr', '?')} Bohr |
| WP energy | {rs.get('wp_energy_ev', '?')} eV |
| WP σ | {rs.get('wp_sigma_bohr', '?')} Bohr |
| WP k₀ | {rs.get('wp_k0_bohr_inv', '?')} |
| WP launch | {rs.get('wp_center_bohr', '?')} Bohr |
| WP state index | {rs.get('wp_state_index', '?')} |
| Norm after injection | {rs.get('norm_after', '?')} |
| max overlap | {rs.get('max_overlap', '?')} |
| dt × N_steps | {rs.get('dt_au','?')} × {rs.get('rt_num_steps','?')} (= {phys['total_time_au']:.3f} a.u.) |
| Wall time | {rs.get('wall_time_s', '?')} s |

## Energy budget (closed-system, end − start)

| Term | Value |
|---|---|
| Δ E_total       | {phys['dE_total_eV']*1e6:+.4f} μeV  (conservation residual) |
| Δ E_kinetic     | {phys['dE_kinetic_eV']:+.4f} eV |
| Δ E_hartree     | {phys['dE_hartree_eV']:+.4f} eV |
| Δ E_xc          | {phys['dE_xc_eV']:+.4f} eV |
| Σ components    | {phys['sum_components_eV']:+.6f} eV  (must equal Δ E_total) |

**Hartree response**: {"depletion anti-wake (Δ E_H < 0)" if phys['dE_hartree_eV'] < 0 else "accumulation wake (Δ E_H > 0)"}

## WP centroid advance (from dipole_z proxy)

| Quantity | Value |
|---|---|
| dipole_z(0)       | {phys['dipole_z0']:+.4f} |
| dipole_z(end)     | {phys['dipole_z1']:+.4f} |
| Advance Δdipole_z | {phys['dipole_z_advance']:+.4f} |

(Bath dipole is nearly constant under WP perturbation, so Δdipole_z is a
proxy for WP centroid motion. For free-particle motion at k₀: expected
advance = k₀ × t.)

## Postprocess pipeline outcome

"""
    for ph in PIPELINE_PHASES:
        flag = pipe_log.get(ph, "skip")
        md += f"- **{ph}**: {flag}\n"
    md += textwrap.dedent(f"""
## Output layout

```
results/analysis/observables/
├── observables_summary.png
├── total_energy_vs_time.png
├── all_energies_vs_time.png
├── current_components_vs_time.png
├── dipole_components_vs_time.png
├── density_fluctuation_l2.png
├── fft_total_energy.png, fft_current_*.png, dipole_spectrum_*.png
├── ks_energies_absolute.gif, ks_energies_delta.gif
├── occupations_absolute.gif, occupations_delta.gif
├── momentum_distribution.gif, momentum_heatmap.png
├── wp_position_vs_time.png, wp_velocity_vs_time.png   (wp_trajectory phase)
├── gamma_transitions/                                  (gamma_transitions phase)
└── state_energy_spectra/                               (state_energy_spectra phase)
```

## Source data

```
results/raw/observables/
├── observables.csv             ({phys['n_frames']} rows)
├── state_energies.csv          (per-orbital E_i(t))
├── occupations_vs_time.csv     (per-orbital f_i(t))
├── momentum_distribution.csv   (n(|k|, t))
├── overlap/                    (WP-only overlap every 10 steps)
├── overlap_proxies/            (proxy O matrix every PROXY_SNAPSHOT_STRIDE)
├── overlap_full/               (full O matrix snapshot at t=0)
├── wp_config.txt, wp_injection_report.txt
└── eigenvalues/                (GS eigenvalues + occupations)
```
""")
    return md


def install_schema_shims() -> list[str]:
    """Bridge two long-standing path-schema mismatches so the pipeline's
    `overlap` and `density`/`density_fourier` phases find our data.

    Our run.cpp writes:
      results/raw/observables/overlap{,_full,_proxies}/
      results/raw/vti/density_{total,system,delta,delta_coarse}/

    But inqview's overlap phase expects results/raw/overlap/, and the
    density phase expects raw/vti/density_rt_*. We add symlinks
    (idempotent) rather than rewrite the C++ — same data, both layouts
    discoverable.
    """
    log: list[str] = []
    pairs = [
        (RESULTS_DIR / "raw" / "overlap",
         RESULTS_DIR / "raw" / "observables" / "overlap"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_total",
         RESULTS_DIR / "raw" / "vti" / "density_total"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_system",
         RESULTS_DIR / "raw" / "vti" / "density_system"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta",
         RESULTS_DIR / "raw" / "vti" / "density_delta"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta_coarse",
         RESULTS_DIR / "raw" / "vti" / "density_delta_coarse"),
    ]
    for link, target in pairs:
        if link.exists() or link.is_symlink():
            continue
        if not target.exists():
            continue
        link.parent.mkdir(parents=True, exist_ok=True)
        link.symlink_to(target.resolve())
        log.append(f"  symlink {link.name} → {target.name}")
    return log


def main() -> int:
    if not RESULTS_DIR.exists():
        print(f"FATAL: {RESULTS_DIR} does not exist", file=sys.stderr)
        return 2

    try:
        from inqview.postprocess import pipeline  # noqa: F401
    except ImportError:
        sys.path.insert(0, "/local/data/public/skcb2/tddft/inq-stack/python")
        from inqview.postprocess import pipeline  # noqa: F401

    print(f"=== analyse.py: {RUN_DIR.name} ===")
    print(f"  results = {RESULTS_DIR}")
    shim_log = install_schema_shims()
    if shim_log:
        print("  schema shims installed:")
        for line in shim_log:
            print(line)
    print(f"  phases  = {', '.join(PIPELINE_PHASES)}\n")

    res = pipeline.run(
        RESULTS_DIR,
        run_name=RUN_DIR.name,
        phases=PIPELINE_PHASES,
        rebuild=False,
        skip_paraview=True,
    )

    pipe_log: dict[str, str] = {}
    for ph in PIPELINE_PHASES:
        if ph in res.ok:        pipe_log[ph] = "[ok]"
        elif ph in res.skipped: pipe_log[ph] = f"[skip] {res.skipped[ph]}"
        elif ph in res.failed:  pipe_log[ph] = f"[fail] {res.failed[ph]}"
        else:                   pipe_log[ph] = "[not run]"

    # density_fourier is not in pipeline._PHASE_FUNCS; call it directly.
    # For the WP run this extracts the axial n_q(t) modes which detect
    # plasmon-like collective bath response (used by the plasmon runs).
    try:
        from inqview.postprocess import density_fourier as _df
        print("\n=== density_fourier (axial n_q(t), m=1..6) ===")
        _df.run(RESULTS_DIR, run_name=RUN_DIR.name, m_max=6, dt_au=0.02)
        pipe_log["density_fourier"] = "[ok]"
    except FileNotFoundError as exc:
        pipe_log["density_fourier"] = f"[skip] {exc}"
        print(f"\ndensity_fourier skipped: {exc}")
    except Exception as exc:
        pipe_log["density_fourier"] = f"[fail] {type(exc).__name__}: {exc}"
        print(f"\ndensity_fourier failed: {exc}")

    # ---- Custom post-pipeline analyses ----
    # Overlap heatmap |O_ij(t_end)|² and effective GS-projected
    # occupations n_i^GS(t_end) = Σ_j f_j |O_ij|² (classical-only force
    # and ΔE-vs-z plots skipped since this is a WP run).
    sys.path.insert(0, str(RUN_DIR.parent / "shared" / "python"))
    from analyse_extras import run_extras
    print("\n=== custom analyses (analyse_extras) ===")
    extras_log = run_extras(RESULTS_DIR, RUN_DIR.name, is_classical=False)
    for k, v in extras_log.items():
        pipe_log[k] = v
        print(f"  {v:<70} {k}")

    rs_keys = ["cell_bohr", "n_electrons", "spacing_bohr",
               "wp_energy_ev", "wp_sigma_bohr", "wp_k0_bohr_inv",
               "wp_center_bohr", "wp_state_index",
               "norm_after", "max_overlap",
               "wall_time_s", "dt_au", "rt_num_steps"]
    rs = {k: read_summary_value(SUMMARY, k, "?") for k in rs_keys}

    phys = physics_block()

    out_md = ANALYSIS / "REPORT.md"
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(render_markdown(phys, rs, pipe_log))
    print(f"\nWrote {out_md}\n")

    print("=== Physics summary ===")
    print(f"  ΔE_total      : {phys['dE_total_eV']*1e6:+.4f} μeV (conservation residual)")
    print(f"  ΔE_kinetic    : {phys['dE_kinetic_eV']:+.4f} eV")
    print(f"  ΔE_hartree    : {phys['dE_hartree_eV']:+.4f} eV  "
          f"({'depletion anti-wake' if phys['dE_hartree_eV']<0 else 'accumulation wake'})")
    print(f"  ΔE_xc         : {phys['dE_xc_eV']:+.4f} eV")
    print(f"  dipole_z(0,end)= {phys['dipole_z0']:+.4f} → {phys['dipole_z1']:+.4f}  "
          f"(Δ = {phys['dipole_z_advance']:+.4f})")
    print()
    print("=== Pipeline ===")
    for ph in PIPELINE_PHASES:
        print(f"  {pipe_log[ph]:<60} {ph}")

    return 0 if not res.failed else 1


if __name__ == "__main__":
    sys.exit(main())
