#!/usr/bin/env python3
"""analyse.py — per-run postprocess for the FREE archetype.

Free-particle WP runs (no jellium bath) — uses only the phases that
make sense for a non-interacting box + WP, plus the new campaign-wide
phases (knudsen_ke, kl_divergence). No GS density structure, no
eigenvalues, no overlap with a multi-state basis.
"""
from __future__ import annotations

import re
import sys
import textwrap
from pathlib import Path

import pandas as pd

HA_TO_EV = 27.211386245988

RUN_DIR     = Path(__file__).resolve().parent
RESULTS_DIR = RUN_DIR / "results"
ANALYSIS    = RESULTS_DIR / "analysis"
SUMMARY     = RESULTS_DIR / "run_summary.txt"

PIPELINE_PHASES: tuple[str, ...] = (
    "summary",
    "layout",
    "observables",
    "occupations",
    "momentum",
    "knudsen_ke",
    "kl_divergence",
    "density",
)


def read_summary_value(path: Path, key: str, default=None):
    if not path.exists():
        return default
    m = re.search(rf"^\s*{re.escape(key)}\s*=\s*(\S+)",
                  path.read_text(), flags=re.MULTILINE)
    if not m:
        return default
    s = m.group(1)
    try:
        return float(s)
    except ValueError:
        return s


def physics_block() -> dict:
    obs_dir = RESULTS_DIR / "raw" / "observables"
    csv = obs_dir / "observables.csv"
    if not csv.exists():
        return {"n_frames": 0, "total_time_au": float("nan")}
    obs = pd.read_csv(csv, comment="#")
    return {
        "n_frames": len(obs),
        "total_time_au": float(obs["time_au"].iloc[-1])
                          if "time_au" in obs.columns else float("nan"),
    }


def render_markdown(phys: dict, rs: dict, pipe_log: dict) -> str:
    md = f"""# Analysis: {RUN_DIR.name}  (FREE archetype)

Auto-generated by `{Path(__file__).name}` — non-interacting free-space WP
propagation. Compare with the matched jellium run in the campaign sweep.

## Run identity

| Field | Value |
|---|---|
| Run dir | `{RUN_DIR}` |
| Cell | {rs.get('cell_bohr', '?')} |
| Spacing | {rs.get('spacing_bohr', '?')} Bohr |
| Theory | non-interacting (no Hartree, no XC) |
| WP energy | {rs.get('wp_energy_ev', '?')} eV |
| WP σ | {rs.get('wp_sigma_bohr', '?')} Bohr |
| WP k₀ | {rs.get('wp_k0_bohr_inv', '?')} |
| WP launch | {rs.get('wp_center_bohr', '?')} Bohr |
| N_steps × dt_au | {rs.get('rt_num_steps','?')} × {rs.get('dt_au','?')} (= {phys['total_time_au']:.3f} a.u.) |

## Postprocess pipeline outcome

"""
    for ph in PIPELINE_PHASES:
        md += f"- **{ph}**: {pipe_log.get(ph, '[not run]')}\n"
    md += textwrap.dedent(f"""
## Expected outputs

```
results/analysis/observables/
├── observables_summary.png, total_energy_vs_time.png, all_energies_vs_time.png
├── energy_kinetic_vs_time.png, energy_hartree_vs_time.png, energy_xc_vs_time.png
├── current_components_vs_time.png, dipole_components_vs_time.png
├── fft_total_energy.png, fft_current_*.png, dipole_spectrum_*.png
├── momentum_distribution.gif, momentum_heatmap.png
├── knudsen_ke_vs_t.png, kl_divergence_vs_t.png   (new campaign phases)
└── density/                                       (only if VTI series present)
```
""")
    return md


def main() -> int:
    if not RESULTS_DIR.exists():
        print(f"FATAL: {RESULTS_DIR} does not exist", file=sys.stderr)
        return 2

    try:
        from inqview.postprocess import pipeline  # noqa: F401
    except ImportError:
        sys.path.insert(0, "/local/data/public/skcb2/tddft/inq-stack/python")
        from inqview.postprocess import pipeline  # noqa: F401

    print(f"=== analyse.py: {RUN_DIR.name} (FREE archetype) ===")
    print(f"  results = {RESULTS_DIR}")
    print(f"  phases  = {', '.join(PIPELINE_PHASES)}\n")

    res = pipeline.run(
        RESULTS_DIR,
        run_name=RUN_DIR.name,
        phases=PIPELINE_PHASES,
        rebuild=False,
        skip_paraview=True,
    )

    pipe_log: dict[str, str] = {}
    for ph in PIPELINE_PHASES:
        if ph in res.ok:        pipe_log[ph] = "[ok]"
        elif ph in res.skipped: pipe_log[ph] = f"[skip] {res.skipped[ph]}"
        elif ph in res.failed:  pipe_log[ph] = f"[fail] {res.failed[ph]}"
        else:                   pipe_log[ph] = "[not run]"

    rs_keys = ["cell_bohr", "spacing_bohr",
               "wp_energy_ev", "wp_sigma_bohr", "wp_k0_bohr_inv",
               "wp_center_bohr", "wp_state_index", "norm_after",
               "wall_time_s", "dt_au", "rt_num_steps"]
    rs = {k: read_summary_value(SUMMARY, k, "?") for k in rs_keys}
    phys = physics_block()

    out_md = ANALYSIS / "REPORT.md"
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(render_markdown(phys, rs, pipe_log))
    print(f"\nWrote {out_md}\n")

    print("=== Pipeline ===")
    for ph in PIPELINE_PHASES:
        print(f"  {pipe_log[ph]:<60} {ph}")

    return 0 if not res.failed else 1


if __name__ == "__main__":
    sys.exit(main())
