#!/usr/bin/env python3
"""analyse.py — per-run postprocess for coronene run_cc_bond.

Self-contained: invokes the inqview postprocess pipeline with EVERY phase
relevant to a coronene WP-LEED TDDFT run, computes the physics summary
(energy budget, WP advance), and writes a markdown REPORT.md plus all the
standard plots/CSVs/GIFs into results/analysis/observables/.

Usage:
    cd <this dir>
    python3 analyse.py

The pipeline phases run here include the WP-specific `wp_trajectory` and
the LEED `screens` phase; jellium-specific phases (`gamma_transitions`,
`knudsen_ke`, `kl_divergence`, `energy_balance`) are excluded.
Specifically:

    summary, gs, layout, observables, eigenvalues_gs, wp_trajectory,
    state_energies, state_energy_spectra, occupations, momentum, density,
    overlap, screens, orbitals
"""
from __future__ import annotations

import re
import sys
import textwrap
from pathlib import Path

import pandas as pd

HA_TO_EV = 27.211386245988

RUN_DIR     = Path(__file__).resolve().parent
RESULTS_DIR = RUN_DIR / "results"
ANALYSIS    = RESULTS_DIR / "analysis"
SUMMARY     = RESULTS_DIR / "run_summary.txt"

# All phases relevant to a coronene WP-LEED TDDFT run.
PIPELINE_PHASES: tuple[str, ...] = (
    "summary",
    "gs",
    "layout",
    "observables",
    "eigenvalues_gs",
    "wp_trajectory",
    "state_energies",
    "state_energy_spectra",
    "occupations",
    "momentum",
    "density",
    "overlap",
    "screens",
    "orbitals",
)


def read_summary_value(path: Path, key: str, default=None):
    if not path.exists():
        return default
    m = re.search(rf"^\s*{re.escape(key)}\s*=\s*(\S+)",
                  path.read_text(), flags=re.MULTILINE)
    if not m:
        return default
    s = m.group(1)
    try:
        return float(s)
    except ValueError:
        return s


def physics_block() -> dict:
    obs_dir = RESULTS_DIR / "raw" / "observables"
    obs = pd.read_csv(obs_dir / "observables.csv")

    wE0  = float(obs["energy_total"].iloc[0])
    wE1  = float(obs["energy_total"].iloc[-1])
    wEk0, wEk1 = float(obs["energy_kinetic"].iloc[0]), float(obs["energy_kinetic"].iloc[-1])
    wEh0, wEh1 = float(obs["energy_hartree"].iloc[0]), float(obs["energy_hartree"].iloc[-1])
    wEx0, wEx1 = float(obs["energy_xc"].iloc[0]),     float(obs["energy_xc"].iloc[-1])

    has_dz = "dipole_z" in obs.columns
    dz0 = float(obs["dipole_z"].iloc[0]) if has_dz else float("nan")
    dz1 = float(obs["dipole_z"].iloc[-1]) if has_dz else float("nan")

    return {
        "dE_total_eV":   (wE1 - wE0) * HA_TO_EV,
        "dE_kinetic_eV": (wEk1 - wEk0) * HA_TO_EV,
        "dE_hartree_eV": (wEh1 - wEh0) * HA_TO_EV,
        "dE_xc_eV":      (wEx1 - wEx0) * HA_TO_EV,
        "sum_components_eV": ((wEk1-wEk0)+(wEh1-wEh0)+(wEx1-wEx0)) * HA_TO_EV,
        "dipole_z0":         dz0,
        "dipole_z1":         dz1,
        "dipole_z_advance":  dz1 - dz0,
        "n_frames":          len(obs),
        "total_time_au":     float(obs["time_au"].iloc[-1]),
    }


def render_markdown(phys: dict, rs: dict, pipe_log: dict) -> str:
    md = f"""# Analysis: {RUN_DIR.name}

Auto-generated by `{Path(__file__).name}`. Re-run any time after
modifying observables to refresh plots.

## Run identity

| Field | Value |
|---|---|
| Run dir | `{RUN_DIR}` |
| System | coronene (C24H12) |
| N_electrons | {rs.get('n_electrons', '?')} |
| Spacing | {rs.get('spacing_bohr', '?')} Bohr |
| WP energy | {rs.get('wp_energy_ev', '?')} eV |
| dt x N_steps | {rs.get('dt_au','?')} x {rs.get('rt_num_steps','?')} (= {phys['total_time_au']:.3f} a.u.) |
| Wall time | {rs.get('wall_time_s', '?')} s |

## Energy budget (closed-system, end - start)

| Term | Value |
|---|---|
| dE_total       | {phys['dE_total_eV']*1e6:+.4f} uEV  (conservation residual) |
| dE_kinetic     | {phys['dE_kinetic_eV']:+.4f} eV |
| dE_hartree     | {phys['dE_hartree_eV']:+.4f} eV |
| dE_xc          | {phys['dE_xc_eV']:+.4f} eV |
| Sum components | {phys['sum_components_eV']:+.6f} eV  (must equal dE_total) |

## WP centroid advance (from dipole_z proxy)

| Quantity | Value |
|---|---|
| dipole_z(0)       | {phys['dipole_z0']:+.4f} |
| dipole_z(end)     | {phys['dipole_z1']:+.4f} |
| Advance d_dipole_z | {phys['dipole_z_advance']:+.4f} |

## Postprocess pipeline outcome

"""
    for ph in PIPELINE_PHASES:
        flag = pipe_log.get(ph, "skip")
        md += f"- **{ph}**: {flag}\n"
    md += textwrap.dedent(f"""
## Output layout

```
results/analysis/observables/
├── observables_summary.png
├── total_energy_vs_time.png
├── all_energies_vs_time.png
├── current_components_vs_time.png
├── dipole_components_vs_time.png
├── fft_total_energy.png, fft_current_*.png, dipole_spectrum_*.png
├── ks_energies_absolute.gif, ks_energies_delta.gif
├── occupations_absolute.gif, occupations_delta.gif
├── momentum_distribution.gif, momentum_heatmap.png
├── wp_position_vs_time.png, wp_velocity_vs_time.png   (wp_trajectory phase)
├── screens/                                            (screens phase)
└── state_energy_spectra/                               (state_energy_spectra phase)
```

## Source data

```
results/raw/observables/
├── observables.csv             ({phys['n_frames']} rows)
├── state_energies.csv          (per-orbital E_i(t))
├── occupations_vs_time.csv     (per-orbital f_i(t))
├── momentum_distribution.csv   (n(|k|, t))
├── overlap/                    (WP-only overlap every 10 steps)
├── wp_config.txt, wp_injection_report.txt
└── eigenvalues/                (GS eigenvalues + occupations)
```
""")
    return md


def install_schema_shims() -> list[str]:
    """Bridge path-schema mismatches so the pipeline's overlap and
    density phases find our data."""
    log: list[str] = []
    pairs = [
        (RESULTS_DIR / "raw" / "overlap",
         RESULTS_DIR / "raw" / "observables" / "overlap"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_total",
         RESULTS_DIR / "raw" / "vti" / "density_total"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_system",
         RESULTS_DIR / "raw" / "vti" / "density_system"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta",
         RESULTS_DIR / "raw" / "vti" / "density_delta"),
        (RESULTS_DIR / "raw" / "vti" / "density_rt_delta_coarse",
         RESULTS_DIR / "raw" / "vti" / "density_delta_coarse"),
    ]
    for link, target in pairs:
        if link.exists() or link.is_symlink():
            continue
        if not target.exists():
            continue
        link.parent.mkdir(parents=True, exist_ok=True)
        link.symlink_to(target.resolve())
        log.append(f"  symlink {link.name} -> {target.name}")
    return log


def main() -> int:
    if not RESULTS_DIR.exists():
        print(f"FATAL: {RESULTS_DIR} does not exist", file=sys.stderr)
        return 2

    try:
        from inqview.pipeline import runner as pipeline  # noqa: F401
    except ImportError:
        sys.path.insert(0, "/local/data/public/skcb2/tddft/inq-stack/python")
        from inqview.pipeline import runner as pipeline  # noqa: F401

    print(f"=== analyse.py: {RUN_DIR.name} ===")
    print(f"  results = {RESULTS_DIR}")
    shim_log = install_schema_shims()
    if shim_log:
        print("  schema shims installed:")
        for line in shim_log:
            print(line)
    print(f"  phases  = {', '.join(PIPELINE_PHASES)}\n")

    res = pipeline.run(
        RESULTS_DIR,
        run_name=RUN_DIR.name,
        phases=PIPELINE_PHASES,
        rebuild=False,
        skip_paraview=True,
    )

    pipe_log: dict[str, str] = {}
    for ph in PIPELINE_PHASES:
        if ph in res.ok:        pipe_log[ph] = "[ok]"
        elif ph in res.skipped: pipe_log[ph] = f"[skip] {res.skipped[ph]}"
        elif ph in res.failed:  pipe_log[ph] = f"[fail] {res.failed[ph]}"
        else:                   pipe_log[ph] = "[not run]"

    rs_keys = ["n_electrons", "spacing_bohr",
               "wp_energy_ev", "wall_time_s", "dt_au", "rt_num_steps"]
    rs = {k: read_summary_value(SUMMARY, k, "?") for k in rs_keys}

    phys = physics_block()

    out_md = ANALYSIS / "REPORT.md"
    out_md.parent.mkdir(parents=True, exist_ok=True)
    out_md.write_text(render_markdown(phys, rs, pipe_log))
    print(f"\nWrote {out_md}\n")

    print("=== Physics summary ===")
    print(f"  dE_total      : {phys['dE_total_eV']*1e6:+.4f} uEV (conservation residual)")
    print(f"  dE_kinetic    : {phys['dE_kinetic_eV']:+.4f} eV")
    print(f"  dE_hartree    : {phys['dE_hartree_eV']:+.4f} eV")
    print(f"  dE_xc         : {phys['dE_xc_eV']:+.4f} eV")
    print(f"  dipole_z(0,end)= {phys['dipole_z0']:+.4f} -> {phys['dipole_z1']:+.4f}  "
          f"(d = {phys['dipole_z_advance']:+.4f})")
    print()
    print("=== Pipeline ===")
    for ph in PIPELINE_PHASES:
        print(f"  {pipe_log[ph]:<60} {ph}")

    return 0 if not res.failed else 1


if __name__ == "__main__":
    sys.exit(main())
