// ============================================================================
// scripts/bulk_ks_stopping_rs4/classical/run.cpp
//
// CLASSICAL half of the bulk-jellium KS-orbital stopping-power twin pair.
// Plan: docs/plans/bulk-jellium-ks-stopping.md (user design lock 2026-07-30).
//
// A classical electron — a Gaussian -1e pseudo-ion of CHARGE std 1.4142 Bohr,
// mass m_e — is launched at z = -32 with v_z = 2.7111 (100 eV) through the same
// fully periodic 40 x 40 x 80 Bohr jellium bath (N = 482, r_s = 3.987) as the
// wavepacket twin, from the SAME ground state, for the SAME 646 steps at
// dt = 0.04. Ion dynamics: FREE EHRENFEST — the electronic forces decelerate the
// projectile, and that deceleration is the measurement.
//
// TWIN PARITY. Every physical parameter is shared with the WP run except the
// projectile's representation. In particular the Gaussian UPF was generated by
// inqview.io.gaussian_psp.generate_gaussian_psp(sigma_wp=2.0), whose charge std
// is sigma_WP/sqrt(2) = 1.4142 — exactly the density std of the WP at t = 0. Both
// projectiles therefore present the IDENTICAL charge cloud exp(-r^2/sigma_WP^2)
// to the bath, and both are labelled sigma = 2
// (.claude/rules/sigma-wp-convention.md).
//
// WHAT THIS RUN MEASURES. The classical reference stopping power
//
//   S_cl = -d(T_ion)/d(z_ion),   T_ion = 1/2 m v_z^2
//
// from electron_track.csv (position + velocity every step). This is the single
// unambiguous number the four KS-orbital definitions of the WP run are compared
// against: here T and s are both classical and there is no choice to make.
//
// T_ion is ALSO available independently as the energy_ion_kinetic column of
// observables.csv (INQ's own bookkeeping), so the two must agree — a free
// consistency check on the ion integrator.
//
// LIGHT PROJECTILE. Per .claude/rules/light-projectile-stopping.md this
// projectile has m = m_e and WILL decelerate substantially: do NOT expect a
// constant velocity, and extract S over the early near-constant-v window rather
// than by regressing the whole trajectory (which would average S over every
// velocity between v0 and whatever it ends at). The analysis window
// t in [4.0, 18.97] a.u. is shared with the WP twin for comparability; analyse.py
// additionally reports the v >= 0.85 v0 sub-window.
//
// NO RESUME (user decision, 2026-07-30). INQ refuses to restart a propagation
// with moving ions: real_time/propagate.hpp:41 asserts ion_propagator
// .static_ions() whenever start_step > 0. A workaround exists (restart at
// start_step = 0 with the remaining step count and relabel, valid ONLY because
// this run has no time-dependent perturbation), but the user chose to drop the
// resume requirement here rather than carry the workaround. A FINAL checkpoint
// is still written so the end state is preserved for inspection; a killed job
// must be re-run from step 0. At 646 steps that is an acceptable exposure.
// ============================================================================

#include <inq/inq.hpp>
#include <inqkit/fields/density.hpp>
#include <inqkit/io/observables_writer.hpp>
#include <inqkit/io/real_field_3d_writer.hpp>
#include <inqkit/jellium/interaction_energies.hpp>   // P/S/B pairwise decomposition
#include <inqkit/jellium/projectile_background_energy.hpp>  // gaussian_density
#include <inqkit/observables/density_delta.hpp>
#include <inqkit/observables/occupations_writer.hpp>
#include <inqkit/observables/state_energy_writer.hpp>
#include <inqkit/real_time/real_time_session.hpp>
#include <inqkit/real_time/step_context.hpp>

#include "../../../shared/configs/bulk_ks_stopping_L40x40x80_rs4.hpp"
#include "../../../shared/cpp/eigenvalues_writer.hpp"
#include "../../../shared/cpp/rt_state.hpp"

#include <chrono>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <string>

using namespace inq;
using namespace inq::magnitude;
using Cfg = jellium::config::Bulk_KS_Stopping_L40x40x80_rs4_Classical;

static std::string iso_now() {
    auto t = std::time(nullptr);
    auto tm = *std::localtime(&t);
    char buf[64];
    std::strftime(buf, sizeof(buf), "%Y-%m-%dT%H:%M:%S", &tm);
    return std::string(buf);
}

static int env_int(char const* k, int dflt) {
    char const* v = std::getenv(k);
    return v ? std::atoi(v) : dflt;
}

int main() {
    auto t_wall0 = std::chrono::steady_clock::now();

    const std::string RUN_NAME = "bulk_ks_stopping_rs4_classical";
    const std::string REPO =
        "/rds/user/skcb2/hpc-work/tddft/inq-tddft-research";
    const std::string GS_DIR = REPO +
        "/ResearchProject/systems/jellium/checkpoints/"
        "gs_L40x40x80_orth_N482_dx0p50";

    const int N_STEPS = env_int("BKS_N_STEPS", Cfg::N_STEPS);

    std::cout << "\n=== " << RUN_NAME << " ===\n"
              << "  cell     = " << Cfg::LX_BOHR << " x " << Cfg::LY_BOHR
              << " x " << Cfg::LZ_BOHR << " Bohr (orthorhombic, PERIODIC xyz)\n"
              << "  N_e      = " << Cfg::N_ELECTRONS
              << "   spacing = " << Cfg::SPACING_BOHR << " Bohr\n"
              << "  proj     : classical electron, Gaussian UPF, m = m_e\n"
              << "  sigma_WP = " << Cfg::WP_SIGMA_BOHR
              << "  => charge std = " << Cfg::WP_SIGMA_BOHR / std::sqrt(2.0)
              << " Bohr\n"
              << "  launch   = (" << Cfg::PROJ_LAUNCH_X << ", "
              << Cfg::PROJ_LAUNCH_Y << ", " << Cfg::PROJ_LAUNCH_Z << ") Bohr"
              << "   v_z = " << Cfg::PROJ_VEL_Z << " Bohr/atu\n"
              << "  dt=" << Cfg::DT_AU << "  N_steps=" << N_STEPS
              << "  t_total=" << (Cfg::DT_AU * N_STEPS) << " a.u.\n"
              << "  fit window = [" << Cfg::FIT_T0_AU << ", " << Cfg::FIT_T1_AU
              << "] a.u.\n"
              << "  pseudo   = " << Cfg::PROJ_PSEUDO_PATH << "\n"
              << "  GS       = " << GS_DIR << "\n\n";

    if (!std::filesystem::exists(GS_DIR)) {
        std::cerr << "FATAL: GS checkpoint missing at " << GS_DIR << "\n";
        return 2;
    }
    if (!std::filesystem::exists(Cfg::PROJ_PSEUDO_PATH)) {
        std::cerr << "FATAL: projectile UPF missing at "
                  << Cfg::PROJ_PSEUDO_PATH << "\n";
        return 2;
    }

    auto cell = systems::cell::orthorhombic(Cfg::LX_BOHR * 1.0_b,
                                            Cfg::LY_BOHR * 1.0_b,
                                            Cfg::LZ_BOHR * 1.0_b).periodic();

    // ----- Insert the one classical-electron pseudo-ion --------------------
    auto ions = systems::ions(cell);
    auto sp_e = ionic::species(Cfg::PROJ_SPECIES_SYMBOL)
                    .pseudo_file(Cfg::PROJ_PSEUDO_PATH)
                    .mass(Cfg::PROJ_MASS_AMU);
    ions.insert(sp_e, {Cfg::PROJ_LAUNCH_X * 1.0_b,
                       Cfg::PROJ_LAUNCH_Y * 1.0_b,
                       Cfg::PROJ_LAUNCH_Z * 1.0_b});
    std::cout << "  Inserted projectile ion, mass_au = "
              << ions.species(0).mass() << " (expect 1.0)\n";

    // ----- Load the bath GS (computed WITHOUT the projectile) --------------
    auto electrons = systems::electrons(
        ions,
        options::electrons{}
            .spacing(Cfg::SPACING_BOHR * 1.0_b)
            .extra_electrons(Cfg::N_ELECTRONS)
            .extra_states(Cfg::EXTRA_STATES)
            .temperature(Cfg::TEMPERATURE_EV * 1.0_eV),
        input::kpoints::gamma());
    electrons.load(GS_DIR);
    std::cout << "  Loaded GS from " << GS_DIR << "\n";

    const std::string OBS = "results/raw/observables";
    const std::string VTI = "results/raw/vti";
    for (auto const& d : {OBS, VTI + "/density_total", VTI + "/density_delta",
                          VTI + "/density_delta_coarse",
                          VTI + "/density_gs_system"})
        std::filesystem::create_directories(d);

    jellium::eigenvalues::copy_from_checkpoint(GS_DIR, OBS + "/eigenvalues");

    // ----- Launch velocity --------------------------------------------------
    ions.velocities()[0] = vector3<double>{Cfg::PROJ_VEL_X,
                                           Cfg::PROJ_VEL_Y,
                                           Cfg::PROJ_VEL_Z};
    const double ke0 = ions.kinetic_energy();
    const double ke0_expect = 0.5 * Cfg::PROJ_VEL_Z * Cfg::PROJ_VEL_Z;
    std::cout << "  Velocity set: v_z = " << Cfg::PROJ_VEL_Z
              << "   KE = " << ke0 << " Ha (expect " << ke0_expect << ")\n";

    // ----- t = 0 analytic gates -------------------------------------------
    {
        int fails = 0;
        auto gate = [&](char const* name, double got, double want, double tol) {
            const bool ok = std::abs(got - want) <= tol;
            std::cout << (ok ? "  [PASS] " : "  [FAIL] ") << name << ": " << got
                      << " (expect " << want << " +/- " << tol << ")\n";
            if (!ok) ++fails;
        };
        std::cout << "\n  --- t=0 analytic gates ---\n";
        gate("projectile mass (a.u.)", ions.species(0).mass(), 1.0, 1.0e-3);
        // 100 eV = 3.674905 Ha; identical to the WP twin's <p>^2/2.
        gate("projectile KE (Ha)", ke0, ke0_expect, 1.0e-6);
        gate("projectile KE (eV)", ke0 * 27.211386, Cfg::WP_EKIN_EV, 1.0e-3);
        gate("launch z (Bohr)", ions.positions()[0][2], Cfg::PROJ_LAUNCH_Z, 1e-9);
        if (fails > 0) {
            std::cerr << "\nFATAL: " << fails << " t=0 gate(s) failed.\n";
            return 4;
        }
        std::cout << "  all t=0 gates PASSED\n\n";
    }

    // ----- Writers ----------------------------------------------------------
    inqkit::io::RealField3DLayout vti_layout{
        .field_name = "density", .include_meta = false,
        .emit_raw = false, .emit_vti = true,
        .vti_format = inqkit::io::VTIWriteOptions::Format::binary};

    {
        inqkit::io::RealField3DWriter gs_wr(VTI + "/density_gs_system",
                                            vti_layout, {.overwrite = true});
        gs_wr.write(inqkit::fields::density::total(electrons),
                    "density_gs_system");
    }
    inqkit::io::RealField3DWriter total_wr(VTI + "/density_total", vti_layout,
                                           {.overwrite = true});

    // FULL energy decomposition — matches the WP twin exactly so the two
    // ledgers are directly differenceable. energy_ion_kinetic IS T_ion here.
    inqkit::io::ObservableSelection sel;
    sel.step = sel.time_au = true;
    sel.energy_total = sel.energy_kinetic = sel.energy_hartree = sel.energy_xc = true;
    sel.energy_external = sel.energy_nonlocal = sel.energy_ion = true;
    sel.energy_ion_kinetic = sel.energy_exact_exchange = true;
    sel.energy_nvxc = sel.energy_eigenvalues = true;
    sel.current_x = sel.current_y = sel.current_z = true;
    sel.dipole_x = sel.dipole_y = sel.dipole_z = true;
    sel.density_l2 = true;
    inqkit::io::ObservablesWriter obs_writer(OBS + "/observables.csv", sel);
    obs_writer.write_header();

    inqkit::observables::StateEnergyWriter state_energy_wr(
        OBS + "/state_energies.csv", /*emit_variance=*/true);
    inqkit::observables::OccupationsWriter occupations_wr(
        OBS + "/occupations_vs_time.csv");

    inqkit::observables::DensityDelta density_delta(
        VTI + "/density_delta", VTI + "/density_delta_coarse",
        {.emit_raw_vti = false, .emit_coarse_vti = true,   // raw delta = n(t)-n(0), exactly recomputable from density_total
         .compute_l2 = true, .coarse_bin_bohr = 3.0});

    // electron_track.csv — projectile position, velocity and KE EVERY step.
    // This is the classical stopping-power measurement; everything else is
    // context. ke_ion_ha is written explicitly so analyse.py never has to
    // re-derive it from v and a mass convention.
    std::ofstream track(OBS + "/electron_track.csv");
    track << std::setprecision(16);
    track << "step,time_au,x,y,z,vx,vy,vz,ke_ion_ha\n";
    {
        auto const& p = ions.positions()[0];
        auto const& v = ions.velocities()[0];
        track << 0 << "," << 0.0 << "," << p[0] << "," << p[1] << "," << p[2]
              << "," << v[0] << "," << v[1] << "," << v[2] << "," << ke0 << "\n";
    }

    {
        auto sys0 = inqkit::fields::density::total(electrons);
        total_wr.write(sys0, 0.0, 0);
    }

    // ----- Real-time callbacks ---------------------------------------------
    // Callback fires at OBS_EVERY so the ENERGY series stays dense: S_classical is
    // fitted to energy_total(x), and thinning it to the VTI cadence would cut the
    // fit window from ~68 points to ~17. The VTI write inside is gated separately
    // on WRITE_EVERY, so storage and the energy cadence are independent.
    // ---- pairwise interaction-energy decomposition (P = classical projectile,
    // S = bath electrons, B = neutralising background) ---------------------
    // BULK: uniform background => poisson(n+) is pure G=0 => phi_plus == 0, so
    // E_SB = E_PB = E_BB = 0. Written as zeros to keep the schema identical to
    // the WP half and to the localised-jellium runs. In bulk the physics is in
    // E_SS, E_PP, E_PS.
    //
    // n_P here is the projectile's GAUSSIAN CHARGE CLOUD, rebuilt at the ion's
    // current position each step: sigma_pot = sigma_WP/sqrt2, matching the UPF
    // (.claude/rules/sigma-wp-convention.md). The classical projectile is NOT in
    // n, so E_SS == INQ energy_hartree exactly - that is the closure gate.
    const double IE_SIGMA_POT = Cfg::WP_SIGMA_BOHR / std::sqrt(2.0);
    inq::basis::field<inq::basis::real_space, double> ie_phiplus(
        electrons.density().basis());
    ie_phiplus.fill(0.0);
    std::ofstream ix;
    if (electrons.root()) {
        ix.open(OBS + "/interactions.csv");
        ix << std::setprecision(12)
           << "step,time_au,proj_z,e_ss,e_pp,e_ps,e_sb,e_pb,e_bb,"
              "e_hartree_inq,norm_slab,norm_proj\n";
    }

    inqkit::RealTimeSession rt_dens(ions, electrons, Cfg::OBS_EVERY);
    rt_dens.add([&](inqkit::StepContext const& ctx) {
        auto sys_f = inqkit::fields::density::total(*ctx.electrons);
        if (ctx.step % Cfg::WRITE_EVERY == 0)
            total_wr.write(sys_f, ctx.time_au, ctx.step);
        const double l2 = density_delta.snapshot(sys_f, ctx.time_au, ctx.step);
        inqkit::StepContext out = ctx;
        out.density_l2 = l2;
        obs_writer.append(out);

        // Pairwise decomposition at the projectile's CURRENT position.
        auto const& pr = ctx.ions->positions()[0];
        inq::vector3<double> ie_c{pr[0], pr[1], pr[2]};
        auto n_proj = inqkit::jellium::gaussian_density(
            ctx.electrons->density().basis(), ie_c, IE_SIGMA_POT);
        auto ct = inqkit::jellium::compute_coulomb(
            ctx.electrons->density(), n_proj, ie_phiplus);
        if (ctx.electrons->root())
            ix << ctx.step << "," << ctx.time_au << "," << pr[2] << ","
               << ct.e_ss << "," << ct.e_pp << "," << ct.e_ps << ","
               << ct.e_sb << "," << ct.e_pb << "," << 0.0 << ","
               << out.energy_hartree << "," << ct.norm_slab << ","
               << ct.norm_p << "\n";
    });

    // Projectile track at EVERY step (cheap: two vector reads).
    inqkit::RealTimeSession rt_track(ions, electrons, 1);
    rt_track.add([&](inqkit::StepContext const& ctx) {
        auto const& p = ctx.ions->positions()[0];
        auto const& v = ctx.ions->velocities()[0];
        const double ke = 0.5 * ctx.ions->species(0).mass() *
                          (v[0]*v[0] + v[1]*v[1] + v[2]*v[2]);
        track << ctx.step << "," << ctx.time_au << ","
              << p[0] << "," << p[1] << "," << p[2] << ","
              << v[0] << "," << v[1] << "," << v[2] << "," << ke << "\n";
    });

    real_time::propagate(
        ions, electrons,
        [&](auto const& data) {
            rt_dens.step(data);
            rt_track.step(data);
            if (data.iter() % (10 * Cfg::WRITE_EVERY) == 0) {
                state_energy_wr.snapshot(data);
                occupations_wr.snapshot(data);
            }
        },
        options::theory{}.lda(),
        options::real_time{}
            .num_steps(N_STEPS)
            .dt(Cfg::DT_AU * 1.0_atomictime)
            .ehrenfest()                 // electronic forces decelerate the ion
            .observables_current()
            .observables_dipole());

    track.flush();

    // ----- Final state ------------------------------------------------------
    // Written for inspection and for the record. NOT a resume point: see the
    // header note — INQ cannot restart a moving-ion propagation.
    electrons.save("results/checkpoint");
    {
        auto const& p = ions.positions()[0];
        auto const& v = ions.velocities()[0];
        jellium::rt_state::write("results/rt_state.txt",
                                 {.last_step   = N_STEPS,
                                  .time_au     = Cfg::DT_AU * N_STEPS,
                                  .dt          = Cfg::DT_AU,
                                  .wp_idx      = -1,
                                  .proj_z      = p[2],
                                  .proj_vz     = v[2],
                                  .proj_mass   = ions.species(0).mass(),
                                  .proj_charge = -1.0});
    }

    const double wall =
        std::chrono::duration<double>(std::chrono::steady_clock::now() - t_wall0).count();

    if (electrons.root()) {
        auto const& p = ions.positions()[0];
        auto const& v = ions.velocities()[0];
        const double ke_end = 0.5 * ions.species(0).mass() *
                              (v[0]*v[0] + v[1]*v[1] + v[2]*v[2]);
        std::ofstream s("results/run_summary.txt");
        s << std::setprecision(16);
        s << "RUN SUMMARY\n===========\n\n"
          << "1. Run identity\n---------------\n"
          << "run_name        = " << RUN_NAME << "\n"
          << "run_type        = classical-electron projectile, bulk jellium "
             "TDDFT (ALDA), free Ehrenfest\n"
          << "plan            = docs/plans/bulk-jellium-ks-stopping.md\n"
          << "date_finished   = " << iso_now() << "\n"
          << "wall_time_s     = " << wall << "\n\n"
          << "3. System configuration\n-----------------------\n"
          << "cell_bohr       = " << Cfg::LX_BOHR << " x " << Cfg::LY_BOHR
          << " x " << Cfg::LZ_BOHR << "\n"
          << "cell_geometry   = orthorhombic, periodic xyz\n"
          << "n_electrons     = " << Cfg::N_ELECTRONS << "\n"
          << "extra_states    = " << Cfg::EXTRA_STATES << "\n"
          << "spacing_bohr    = " << Cfg::SPACING_BOHR << "\n"
          << "cutoff_ha       = " << Cfg::CUTOFF_HA << "\n"
          << "xc_functional   = LDA (ALDA in TDDFT)\n"
          << "gs_checkpoint   = " << GS_DIR << "\n\n"
          << "5. Projectile configuration\n---------------------------\n"
          << "projectile_kind = classical electron (Gaussian UPF + m_e mass)\n"
          << "pseudo_file     = " << Cfg::PROJ_PSEUDO_PATH << "\n"
          << "sigma_wp_bohr   = " << Cfg::WP_SIGMA_BOHR << "\n"
          << "sigma_charge    = " << Cfg::WP_SIGMA_BOHR / std::sqrt(2.0) << "\n"
          << "mass_au         = " << ions.species(0).mass() << "\n"
          << "launch_bohr     = " << Cfg::PROJ_LAUNCH_X << " "
          << Cfg::PROJ_LAUNCH_Y << " " << Cfg::PROJ_LAUNCH_Z << "\n"
          << "velocity_atu    = " << Cfg::PROJ_VEL_Z << "\n"
          << "projectile_ke_ev= " << Cfg::WP_EKIN_EV << "\n"
          << "ion_dynamics    = ehrenfest (free; electronic forces decelerate)\n"
          << "final_z_bohr    = " << p[2] << "\n"
          << "final_vz_atu    = " << v[2] << "\n"
          << "final_ke_ha     = " << ke_end << "\n"
          << "ke_lost_ev      = " << (ke0 - ke_end) * 27.211386 << "\n\n"
          << "6. Real-time configuration\n--------------------------\n"
          << "rt_num_steps    = " << N_STEPS << "\n"
          << "dt_au           = " << Cfg::DT_AU << "\n"
          << "total_time_au   = " << (Cfg::DT_AU * N_STEPS) << "\n"
          << "write_every     = " << Cfg::WRITE_EVERY << "\n\n"
          << "7. Analysis window\n------------------\n"
          << "fit_t0_au       = " << Cfg::FIT_T0_AU << "\n"
          << "fit_t1_au       = " << Cfg::FIT_T1_AU << "\n"
          << "plasma_period_au= 49.39\n"
          << "plasma_period_note = EXCEEDS the run: S is initial-drag, not "
             "steady-state\n\n"
          << "9. End-of-run diagnostics\n-------------------------\n"
          << "resume_supported= false (INQ cannot restart moving ions)\n"
          << "run_completed   = true\n";

        std::cout << "\n  Projectile: z " << Cfg::PROJ_LAUNCH_Z << " -> " << p[2]
                  << " Bohr,  v_z " << Cfg::PROJ_VEL_Z << " -> " << v[2]
                  << ",  KE lost = " << (ke0 - ke_end) * 27.211386 << " eV\n";
    }

    std::cout << "Done. Wall time " << wall << " s.\n";
    return 0;
}
