#!/usr/bin/env python3
"""analyse.py — per-run post-processing for the WP-CAP energy-plateau campaign.

Produces (each section independent + non-fatal):
  1. energy_vs_time.png            total + ALL decomposed KS energy components vs t
  2. energy_delta_components.png   ΔE(t)=E(t)-E(0) for every KS component
  3. energy_delta_pairwise.png     ΔE(t) for pairwise E_ss/E_ps/E_pp/E_sb/E_pb
  4. norm_vs_time.png              N_total(t)  (flat=conserved; decays=CAP absorbing)
  5. momentum_evolution.png        WP |n(k,t)| carpet  (from momentum_distribution.csv)
  6. density GIF battery            canonical make_density_gif_battery (rule-mandated)
  7. run_report.ipynb               notebook embedding the GIF (top) + PNGs

Usage:
  analyse.py <results_dir> --label wp --dt 0.02 --slab-face 12.5 --cap-inner 60
             [--title "..."] [--out <dir>]
"""
from __future__ import annotations
import argparse, base64, glob, os, sys
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HA_EV = 27.211386245988


def _log(m): print(f"[analyse] {m}", flush=True)


def plot_energy(obs: Path, out: Path, title: str):
    df = pd.read_csv(obs)
    t = df["time_au"].to_numpy()
    comps = [c for c in ("kinetic", "hartree", "external", "non_local", "xc",
                         "exact_exchange", "ion", "ion_kinetic") if c in df]
    fig, ax = plt.subplots(figsize=(7.0, 4.2))
    ax.plot(t, df["total"] * HA_EV, "k-", lw=2.2, label="total", zorder=5)
    for c in comps:
        if np.any(np.abs(df[c]) > 1e-9):
            ax.plot(t, df[c] * HA_EV, lw=1.3, label=c)
    ax.set_xlabel("time (a.u.)"); ax.set_ylabel("energy (eV)")
    ax.set_title(title); ax.legend(fontsize=8, ncol=2)
    d0 = (df["total"].iloc[-1] - df["total"].iloc[0]) * HA_EV
    ax.text(0.02, 0.02, f"ΔE_total = {d0:+.2f} eV", transform=ax.transAxes,
            fontsize=8, va="bottom")
    fig.tight_layout(); fig.savefig(out, dpi=140); plt.close(fig)
    _log(f"wrote {out.name}  (ΔE_total={d0:+.2f} eV)")
    return d0


def plot_norm(obs: Path, out: Path, title: str):
    df = pd.read_csv(obs)
    if "N_total" not in df:
        return
    fig, ax = plt.subplots(figsize=(7.0, 3.4))
    ax.plot(df["time_au"], df["N_total"], "b-", lw=1.8)
    ax.set_xlabel("time (a.u.)"); ax.set_ylabel("N electrons")
    ax.set_title(title); fig.tight_layout(); fig.savefig(out, dpi=140); plt.close(fig)
    _log(f"wrote {out.name}")


def plot_momentum(mom: Path, out: Path, title: str):
    df = pd.read_csv(mom, comment="#")
    piv = df.pivot_table(index="time_au", columns="k_bohr_inv", values="n_wp")
    T = piv.index.to_numpy(); K = piv.columns.to_numpy(); Z = piv.to_numpy()
    fig, ax = plt.subplots(figsize=(7.0, 4.0))
    im = ax.pcolormesh(T, K, Z.T, shading="auto", cmap="inferno")
    ax.set_xlabel("time (a.u.)"); ax.set_ylabel("k (1/Bohr)")
    ax.set_title(title); fig.colorbar(im, ax=ax, label="|n_wp(k)|")
    fig.tight_layout(); fig.savefig(out, dpi=140); plt.close(fig)
    _log(f"wrote {out.name}")


def make_gifs(results_dir: Path, out: Path, label: str, dt: float,
              slab_face: float, cap_inner: float, title: str,
              per_frame_norm_wp: bool = False, cap_lines=None):
    from inqview.visualisation.density_gifs import make_density_gif_battery
    gifs, _ = make_density_gif_battery(
        str(results_dir), str(out), run_label=label, dt=dt,
        slab_face=slab_face, cap_inner=cap_inner, run_title=title, frames_max=30,
        per_frame_norm_wp=per_frame_norm_wp, cap_lines=cap_lines)
    _log(f"built {len(gifs)} density GIFs")
    return [g[2] for g in gifs]


def build_notebook(out_dir: Path, title: str, pngs: list[Path], gifs: list[Path]):
    import nbformat as nbf
    from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell, new_output
    nb = new_notebook()
    cells = [new_markdown_cell(f"# {title}\n\nAutogenerated run report — "
                              "density evolution (top), energy decomposition, momentum.")]

    def img_output(path: Path, mime: str):
        data = base64.b64encode(path.read_bytes()).decode()
        return new_output("display_data", data={mime: data}, metadata={})

    # density GIF(s) at the TOP (rule: first-read visual intuition, embedded)
    for g in gifs:
        c = new_code_cell(f'from IPython.display import Image\nImage(filename="{g.name}")')
        c.outputs = [img_output(g, "image/gif")]
        c.execution_count = None
        cells.append(new_markdown_cell(f"### {g.stem}"))
        cells.append(c)
    # static PNGs
    for p in pngs:
        c = new_code_cell(f'Image(filename="{p.name}")')
        c.outputs = [img_output(p, "image/png")]
        cells.append(new_markdown_cell(f"### {p.stem}"))
        cells.append(c)
    nb.cells = cells
    nbp = out_dir / "run_report.ipynb"
    nbf.write(nb, str(nbp))
    _log(f"wrote {nbp.name}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("results_dir")
    ap.add_argument("--label", default="wp")
    ap.add_argument("--dt", type=float, default=0.02)
    ap.add_argument("--slab-face", type=float, default=12.5)
    ap.add_argument("--cap-inner", type=float, default=60.0)
    ap.add_argument("--title", default=None)
    ap.add_argument("--out", default=None)
    ap.add_argument("--per-frame-norm-wp", action="store_true",
                    help="normalise the WP density GIF linear panel per-frame so a "
                         "strongly-dispersing wavepacket stays visible as it moves")
    ap.add_argument("--cap-lines", default=None,
                    help="comma-separated z-values for dashed CAP/slab lines "
                         "(overrides symmetric ±slab_face/±cap_inner; use for a "
                         "one-sided CAP, e.g. '30,40')")
    a = ap.parse_args()
    cap_lines = tuple(float(z) for z in a.cap_lines.split(",")) if a.cap_lines else None

    results = Path(a.results_dir)
    out = Path(a.out) if a.out else results / "report"
    out.mkdir(parents=True, exist_ok=True)
    obs = results / "raw" / "observables"
    title = a.title or results.name
    pngs, gifs = [], []

    # energies*.csv may be segmented (resume); concat in step order
    en_files = sorted(glob.glob(str(obs / "energies*.csv")))
    if en_files:
        try:
            dfs = [pd.read_csv(f) for f in en_files]
            merged = pd.concat(dfs).drop_duplicates("step").sort_values("step")
            merged_path = obs / "energies_merged.csv"
            merged.to_csv(merged_path, index=False)
            for fn, plot in (("energy_vs_time.png", plot_energy),
                             ("norm_vs_time.png", plot_norm)):
                try:
                    plot(merged_path, out / fn, title); pngs.append(out / fn)
                except Exception as e:
                    _log(f"{fn} failed: {e}")
        except Exception as e:
            _log(f"energy load failed: {e}")

        # ΔE component + pairwise electrostatic decomposition (needs density frames)
        try:
            import energy_decomposition as ed
            merged_path = obs / "energies_merged.csv"
            ed.plot_energy_delta(merged_path, out / "energy_delta_components.png", title)
            pngs.append(out / "energy_delta_components.png")
            try:
                ed.compute_interactions(results)   # writes interactions.csv (closure-gated)
                ed.plot_pairwise_delta(obs / "interactions.csv",
                                       out / "energy_delta_pairwise.png", title)
                pngs.append(out / "energy_delta_pairwise.png")
            except Exception as e:
                _log(f"pairwise decomposition failed: {e}")
        except Exception as e:
            _log(f"energy-delta plots failed: {e}")

    mom = sorted(glob.glob(str(obs / "momentum_distribution*.csv")))
    if mom:
        try:
            plot_momentum(Path(mom[0]), out / "momentum_evolution.png", title)
            pngs.append(out / "momentum_evolution.png")
        except Exception as e:
            _log(f"momentum failed: {e}")

    try:
        gifs = [Path(g) for g in make_gifs(results, out, a.label, a.dt,
                                           a.slab_face, a.cap_inner, title,
                                           per_frame_norm_wp=a.per_frame_norm_wp,
                                           cap_lines=cap_lines)]
    except Exception as e:
        _log(f"density GIF failed: {e}")

    try:
        build_notebook(out, title, [p for p in pngs if p.exists()],
                       [g for g in gifs if g.exists()])
    except Exception as e:
        _log(f"notebook failed: {e}")

    _log(f"done -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
