// Coronene (C24H12) electron wavepacket scattering — TDDFT simulation
//
// Method: Tsubonoya, Hu, Watanabe, PRB 90, 035416 (2014)
//   - Ground-state KS orbitals computed first
//   - Gaussian WP injected as extra (N+1)th orbital with occupation = 1
//   - All orbitals propagated under TDKS Hamiltonian
//   - Accumulated density on observation plane gives LEED pattern
//
// Phase 1: ground state SCF (current)
// Phase 2: WP injection + TDDFT propagation (stub — compile check only)
// Phase 3: full propagation + LEED accumulation (todo)

#include <inq/inq.hpp>
#include <cmath>
#include <iostream>
#include <fstream>

int main(){
    using namespace inq;
    using namespace inq::magnitude;

    // ── Box dimensions (from paper: 18.4 × 18.4 × 31.7 Å) ──────────────────
    // = 34.76 × 34.76 × 59.91 bohr
    const double Lx = 34.76, Ly = 34.76, Lz = 59.91;  // bohr

    // ── Coronene geometry ────────────────────────────────────────────────────
    // C24H12 in the xy-plane (z=0), centred at origin.
    // D6h symmetry. C-C = 1.421 Å, C-H = 1.086 Å.
    // Generated by gen_geometry.py (analytical, verified: 30 C-C + 12 C-H bonds).
    // Reference: aromatic bond lengths from standard DFT benchmark sets.
    auto ions = systems::ions(systems::cell::orthorhombic(Lx*1.0_b, Ly*1.0_b, Lz*1.0_b).finite());

    // C atoms — shell 1 (inner ring, 6 atoms)
    ions.insert("C", { 2.685301_b,  0.000000_b, 0.0_b});
    ions.insert("C", { 1.342650_b,  2.325539_b, 0.0_b});
    ions.insert("C", {-1.342650_b,  2.325539_b, 0.0_b});
    ions.insert("C", {-2.685301_b,  0.000000_b, 0.0_b});
    ions.insert("C", {-1.342650_b, -2.325539_b, 0.0_b});
    ions.insert("C", { 1.342650_b, -2.325539_b, 0.0_b});

    // C atoms — shell 2 (ring junctions, 6 atoms)
    ions.insert("C", { 5.370601_b,  0.000000_b, 0.0_b});
    ions.insert("C", { 2.685301_b,  4.651077_b, 0.0_b});
    ions.insert("C", {-2.685301_b,  4.651077_b, 0.0_b});
    ions.insert("C", {-5.370601_b,  0.000000_b, 0.0_b});
    ions.insert("C", {-2.685301_b, -4.651077_b, 0.0_b});
    ions.insert("C", { 2.685301_b, -4.651077_b, 0.0_b});

    // C atoms — shell 3 (perimeter, 12 atoms)
    ions.insert("C", { 6.713252_b,  2.325539_b, 0.0_b});
    ions.insert("C", { 5.370601_b,  4.651077_b, 0.0_b});
    ions.insert("C", { 1.342650_b,  6.976616_b, 0.0_b});
    ions.insert("C", {-1.342650_b,  6.976616_b, 0.0_b});
    ions.insert("C", {-5.370601_b,  4.651077_b, 0.0_b});
    ions.insert("C", {-6.713252_b,  2.325539_b, 0.0_b});
    ions.insert("C", {-6.713252_b, -2.325539_b, 0.0_b});
    ions.insert("C", {-5.370601_b, -4.651077_b, 0.0_b});
    ions.insert("C", {-1.342650_b, -6.976616_b, 0.0_b});
    ions.insert("C", { 1.342650_b, -6.976616_b, 0.0_b});
    ions.insert("C", { 5.370601_b, -4.651077_b, 0.0_b});
    ions.insert("C", { 6.713252_b, -2.325539_b, 0.0_b});

    // H atoms (12 atoms, bonded to perimeter C)
    ions.insert("H", { 8.652438_b,  2.997293_b, 0.0_b});
    ions.insert("H", { 6.921951_b,  5.994585_b, 0.0_b});
    ions.insert("H", { 1.730488_b,  8.991878_b, 0.0_b});
    ions.insert("H", {-1.730488_b,  8.991878_b, 0.0_b});
    ions.insert("H", {-6.921951_b,  5.994585_b, 0.0_b});
    ions.insert("H", {-8.652438_b,  2.997293_b, 0.0_b});
    ions.insert("H", {-8.652438_b, -2.997293_b, 0.0_b});
    ions.insert("H", {-6.921951_b, -5.994585_b, 0.0_b});
    ions.insert("H", {-1.730488_b, -8.991878_b, 0.0_b});
    ions.insert("H", { 1.730488_b, -8.991878_b, 0.0_b});
    ions.insert("H", { 6.921951_b, -5.994585_b, 0.0_b});
    ions.insert("H", { 8.652438_b, -2.997293_b, 0.0_b});

    // ── PHASE 1: Ground state SCF ────────────────────────────────────────────
    // extra_states(1) reserves one unoccupied orbital slot for the WP orbital.
    // Coronene has 108 valence electrons → 54 doubly-occupied KS orbitals.
    auto electrons = systems::electrons(ions,
        options::electrons{}.cutoff(30.0_Ha).extra_states(1));

    ground_state::initial_guess(ions, electrons);

    auto result = ground_state::calculate(ions, electrons,
        options::theory{}.lda(),
        options::ground_state{}.energy_tolerance(1e-6_Ha).max_steps(300));

    if(electrons.root()){
        std::cout << "\n=== Ground state results ===\n";
        std::cout << "  Total energy : " << result.energy.total()   << " Ha\n";
        std::cout << "  Kinetic      : " << result.energy.kinetic() << " Ha\n";
        std::cout << "  XC (LDA)     : " << result.energy.xc()     << " Ha\n";
        std::cout << "  Ion-ion      : " << result.energy.ion()     << " Ha\n";
        std::cout << "  SCF steps    : " << result.total_iter       << "\n";
        std::cout << "  Num states   : " << electrons.kpin()[0].spinor_set_size() << "\n";
    }

    // ── PHASE 2: WP injection ────────────────────────────────────────────────
    // Gaussian WP directed toward flake (−z direction).
    // ψ^WP(r) = N · exp(−|r−b|²/(2d²)) · exp(−i k₀ z)
    //   d   = 0.53 Å = 1.001 bohr   (WP width, paper eq. 1)
    //   D   = 6.35 Å = 12.0 bohr    (impact distance above flake)
    //   E_kin = 200 eV = 7.35 Ha
    //   k₀  = sqrt(2 E_kin)          (= 3.83 bohr⁻¹, toward −z)
    //   N   = (π d²)^{-3/4}          (normalisation)
    //
    // Reference: Tsubonoya et al., PRB 90, 035416 (2014) eq. 1
    {
        const double d_wp   = 1.001;              // bohr
        const double D      = 12.0;               // bohr, above flake
        const double Ekin   = 7.349806499;        // 200 eV in Ha
        const double k0     = std::sqrt(2.0 * Ekin);   // ≈ 3.832 bohr⁻¹
        const double norm_wp = std::pow(M_PI * d_wp * d_wp, -0.75);

        // WP centre: (0, 0, +D) — above flake along z
        const double bx = 0.0, by = 0.0, bz = D;

        auto & phi   = electrons.kpin()[0];
        auto & basis = phi.basis();
        int Nx = basis.cubic_part(0).local_size();
        int Ny = basis.cubic_part(1).local_size();
        int Nz = basis.cubic_part(2).local_size();
        auto po = basis.point_op();

        // Index of WP orbital: last state (0-based local index in set_part)
        int ist_wp_local = phi.set_part().local_size() - 1;

        auto hc = phi.hypercubic();

        // Write WP wavefunction into last extra-state orbital
        for(int ix = 0; ix < Nx; ix++){
            for(int iy = 0; iy < Ny; iy++){
                for(int iz = 0; iz < Nz; iz++){
                    auto r = po.rvector_cartesian(ix, iy, iz);
                    double dx = r[0] - bx;
                    double dy = r[1] - by;
                    double dz = r[2] - bz;
                    double r2 = dx*dx + dy*dy + dz*dz;
                    double amp   = norm_wp * std::exp(-r2 / (2.0 * d_wp * d_wp));
                    double phase = -k0 * r[2];   // propagating in −z direction
                    hc[ix][iy][iz][ist_wp_local] = complex(amp * std::cos(phase),
                                                            amp * std::sin(phase));
                }
            }
        }

        // Set WP orbital occupation = 1.0 (singly occupied; paper: one incident electron)
        // occupations()[ikpt][ist]: 2D array [kpoint][local_state_index]
        electrons.occupations()[0][ist_wp_local] = 1.0;

        if(electrons.root()){
            // Compute WP norm: sum |psi|^2 * dV
            double dV = basis.volume_element();
            double norm_check = 0.0;
            for(int ix = 0; ix < Nx; ix++)
                for(int iy = 0; iy < Ny; iy++)
                    for(int iz = 0; iz < Nz; iz++)
                        norm_check += norm(hc[ix][iy][iz][ist_wp_local]) * dV;
            std::cout << "\n=== WP injection ===\n";
            std::cout << "  d_wp  = " << d_wp << " bohr  (" << d_wp/1.8897 << " Å)\n";
            std::cout << "  D     = " << D    << " bohr  (" << D/1.8897    << " Å)\n";
            std::cout << "  k0    = " << k0   << " bohr^-1  (E_kin = 200 eV)\n";
            std::cout << "  <psi|psi> = " << norm_check << "  (expect ≈ 1.0)\n";
        }
    }

    return 0;
}
